import { MenuItem, Translations } from './types';

export const translations: Translations = {
    th: {
        nav_dash: "แดชบอร์ด & ข้อมูลเชิงลึก",
        nav_menu: "เจาะลึกเมนูอาหาร",
        nav_bev: "เครื่องดื่ม",
        nav_dash_short: "แดชบอร์ด",
        nav_menu_short: "เมนู",
        nav_bev_short: "เครื่องดื่ม",
        filter_all: "ทั้งหมด",
        filter_rec: "แนะนำ (ปลอดภัย)",
        filter_avoid: "ควรเลี่ยง",
        cat_all: "ทุกหมวดหมู่",
        th_menu: "เมนูอาหาร",
        th_cat: "หมวดหมู่",
        th_key: "จุดเด่น",
        th_val: "มูลค่าตลาด",
        th_status: "สถานะ",
        click_hint: "คลิกที่แถวเพื่อดูส่วนผสมและโภชนาการอย่างละเอียด",
        modal_ing: "ส่วนประกอบหลัก",
        modal_nutri_grid: "ข้อมูลโภชนาการ (โดยประมาณ)",
        modal_nutri_highlight: "จุดเด่นทางโภชนาการ",
        modal_cost: "ต้นทุน (ครึ่งจาน)",
        modal_cost_sub: "ประมาณการต้นทุน",
        modal_val: "มูลค่าตลาด",
        modal_val_sub: "ราคาหน้าร้านทั่วไป",
        modal_advice: "คำแนะนำเฉพาะบุคคล (50+)",
        modal_close: "เข้าใจแล้ว",
        about_title: "เกี่ยวกับ Vantage Point",
        about_sub: "บรรยากาศแบบ European Mercantile",
        about_atmosphere: "บรรยากาศและคอนเซปต์",
        about_atm_desc: "Vantage Point (QSNCC) นำเสนอประสบการณ์แบบ <strong>\"European Mercantile\"</strong> ที่ผสานความหรูหราเข้ากับความมีชีวิตชีวาของตลาดอาหารยุโรป จุดเด่นสำคัญคือรูปแบบ <strong>\"A La Carte Buffet\"</strong> ที่แตกต่างจากบุฟเฟ่ต์ทั่วไป อาหารทุกจานจะถูก <em>\"ปรุงสดใหม่จานต่อจาน\" (Made-to-order)</em> เมื่อคุณสั่ง ทำให้ได้คุณภาพอาหารระดับภัตตาคาร ไม่มีการทำทิ้งไว้ในถาดอุ่นร้อน ซึ่งช่วยรักษาคุณค่าทางโภชนาการและรสชาติที่ดีที่สุด",
        about_why: "ทำไมถึงเหมาะกับวัย 50+",
        about_why_desc: "ความพิเศษของที่นี่คือความหลากหลายของเมนูยุโรปที่ใช้วัตถุดิบนำเข้า (Premium Ingredients) เช่น ทรัฟเฟิล, ชีสนำเข้า และผักสดปลอดสารพิษ การสั่งแบบจานต่อจานช่วยให้เรา <strong>\"กำหนดปริมาณการทานได้เอง\"</strong> (เช่น สั่งมาแบ่งกันชิม) เหมาะอย่างยิ่งสำหรับผู้ที่ต้องการควบคุมปริมาณแป้งและไขมัน แต่ยังต้องการลิ้มรสชาติที่หลากหลาย",
        stat_total: "รายการอาหารทั้งหมด",
        stat_safe: "ปลอดภัย (ไม่เนื้อ/ปลา/ดิบ)",
        stat_value: "มูลค่าที่ทานได้จริง",
        stat_avoid: "ควรเลี่ยง (ผิดเงื่อนไข)",
        plan_title: "แผนการกินเชิงกลยุทธ์",
        step1_t: "Warm Up", step1_d: "ช่วงเตรียมพร้อม",
        step2_t: "Green & Light", step2_d: "ช่วงเติมไฟเบอร์",
        step3_t: "Main Protein", step3_d: "ช่วงโปรตีนเน้นๆ",
        step4_t: "Premium Carbs", step4_d: "ช่วงแป้งพรีเมียม",
        step5_t: "Closing", step5_d: "ช่วงล้างปากช่วยย่อย",
        bev_advice_title: "คำแนะนำการดื่ม",
        bev_advice_desc: "เพื่อความคุ้มค่าและสุขภาพ: <span class='font-semibold bg-amber-100 px-1'>งดน้ำอัดลมที่มีน้ำตาล</span> (ตัดกำลัง), เน้น <span class='font-semibold bg-amber-100 px-1'>Chang Cold Brew</span> หรือ <span class='font-semibold bg-amber-100 px-1'>น้ำเปล่า/โซดา</span> เพื่อล้างลิ้น และปิดท้ายด้วย <span class='font-semibold bg-amber-100 px-1'>กาแฟร้อน</span> เพื่อช่วยย่อยไขมัน",
        bev_soft: "น้ำอัดลม/น้ำเปล่า",
        bev_mock: "ม็อกเทล",
        bev_coffee: "กาแฟ (ร้อนเท่านั้น)",
        bev_spec: "เครื่องดื่มพิเศษ",
        nutri_cal: "พลังงาน",
        nutri_prot: "โปรตีน",
        nutri_fat: "ไขมัน",
        nutri_carb: "คาร์บ",
        nutri_sugar: "น้ำตาล"
    },
    en: {
        nav_dash: "Dashboard & Insights",
        nav_menu: "Menu Intelligence",
        nav_bev: "Beverages",
        nav_dash_short: "Dashboard",
        nav_menu_short: "Menu",
        nav_bev_short: "Drinks",
        filter_all: "All",
        filter_rec: "Recommended (Safe)",
        filter_avoid: "Avoid",
        cat_all: "All Categories",
        th_menu: "Menu Item",
        th_cat: "Category",
        th_key: "Highlight",
        th_val: "Market Value",
        th_status: "Status",
        click_hint: "Click row for detailed ingredients & nutrients",
        modal_ing: "Main Ingredients",
        modal_nutri_grid: "Nutrition Facts (Est.)",
        modal_nutri_highlight: "Nutritional Highlight",
        modal_cost: "Cost (Half Portion)",
        modal_cost_sub: "Estimated Cost",
        modal_val: "Market Value",
        modal_val_sub: "A La Carte Price",
        modal_advice: "Expert Advice (50+)",
        modal_close: "Close",
        about_title: "About Vantage Point",
        about_sub: "European Mercantile Concept",
        about_atmosphere: "Atmosphere & Concept",
        about_atm_desc: "Vantage Point (QSNCC) offers a <strong>\"European Mercantile\"</strong> experience, blending luxury with the liveliness of European food markets. A key highlight is the <strong>\"A La Carte Buffet\"</strong> style. Unlike typical buffets, every dish is <em>\"Made-to-order\"</em>, ensuring restaurant-quality freshness and nutrition, avoiding food sitting in warmers.",
        about_why: "Why it fits 50+",
        about_why_desc: "This venue excels with diverse European menus using Premium Ingredients like truffle, imported cheeses, and pesticide-free vegetables. The made-to-order style allows you to <strong>\"Control Portions\"</strong> (e.g., sharing tasting portions), perfect for controlling carbs and fats while enjoying variety.",
        stat_total: "Total Menu Items",
        stat_safe: "Safe (No Beef/Fish/Raw)",
        stat_value: "Est. Market Value",
        stat_avoid: "Avoid (Restricted)",
        plan_title: "Strategic Eating Plan",
        step1_t: "Warm Up", step1_d: "Preparation Phase",
        step2_t: "Green & Light", step2_d: "Fiber Loading",
        step3_t: "Main Protein", step3_d: "High Value Proteins",
        step4_t: "Premium Carbs", step4_d: "Taste Portion Only",
        step5_t: "Closing", step5_d: "Digestif Phase",
        bev_advice_title: "Drinking Strategy",
        bev_advice_desc: "For value & health: <span class='font-semibold bg-amber-100 px-1'>Skip Sugary Sodas</span> (filler), focus on <span class='font-semibold bg-amber-100 px-1'>Chang Cold Brew</span> or <span class='font-semibold bg-amber-100 px-1'>Water/Soda</span> to cleanse palate. Finish with <span class='font-semibold bg-amber-100 px-1'>Hot Coffee</span> to aid fat digestion.",
        bev_soft: "Soft Drinks",
        bev_mock: "Mocktails",
        bev_coffee: "Coffee (Hot Only)",
        bev_spec: "Special Drink",
        nutri_cal: "Calories",
        nutri_prot: "Protein",
        nutri_fat: "Fat",
        nutri_carb: "Carbs",
        nutri_sugar: "Sugar"
    }
};

export const menuDB: MenuItem[] = [
    // SALAD
    { n: "Baby Kale Salad", c: "Salad", h: "Vitamin K, Fiber", cost: 25, val: 120, s: 2, 
      r_th: "Kale คือ Superfood ช่วยระบบขับถ่ายและบำรุงกระดูก", 
      r_en: "Kale is a Superfood, aiding digestion and bone health.",
      ing_th: "เบบี้เคล, น้ำมันมะกอก, เลมอน, พาเมซานชีส, ถั่ววอลนัท", ing_en: "Baby Kale, Olive Oil, Lemon, Parmesan, Walnuts",
      kcal: 85, protein: "3g", fat: "6g", carbs: "5g" },
    { n: "Avocado & Orange Salad", c: "Salad", h: "Healthy Fats, Vit C", cost: 35, val: 160, s: 3, 
      r_th: "เมนูสุขภาพอันดับ 1 ในไลน์นี้ ไขมันดีลดคอเลสเตอรอล", 
      r_en: "#1 Healthy Choice here. Good fats reduce cholesterol.",
      ing_th: "อะโวคาโด, ส้ม, ผักสลัดรวม, น้ำสลัดบัลซามิก", ing_en: "Avocado, Orange segments, Mixed Greens, Balsamic Dressing",
      kcal: 140, protein: "2g", fat: "12g", carbs: "10g" },
    { n: "Shrimp Salad", c: "Salad", h: "Lean Protein", cost: 40, val: 150, s: 2, 
      r_th: "กุ้งเป็นแหล่งโปรตีนที่ดี แต่ระวังน้ำสลัดครีมเยอะเกินไป", 
      r_en: "Shrimp is great lean protein, but go easy on the creamy dressing.",
      ing_th: "กุ้งลวก, ผักคอส, มะเขือเทศราชินี, น้ำสลัดครีม", ing_en: "Boiled Shrimp, Cos Lettuce, Cherry Tomatoes, Cream Dressing",
      kcal: 180, protein: "15g", fat: "10g", carbs: "6g" },
    { n: "Quinoa Salad", c: "Salad", h: "Complete Protein", cost: 20, val: 140, s: 3, 
      r_th: "ควินัวให้โปรตีนและไฟเบอร์สูงมาก อิ่มท้องแต่ไม่อ้วน", 
      r_en: "Quinoa offers high protein & fiber. Filling but not fattening.",
      ing_th: "ควินัว 3 สี, แตงกวา, พริกหวาน, น้ำมันมะกอก", ing_en: "Tricolor Quinoa, Cucumber, Bell Peppers, Olive Oil",
      kcal: 120, protein: "5g", fat: "4g", carbs: "18g" },
    { n: "Salmon Gravlax Salad", c: "Salad", h: "Omega-3 (Raw Fish)", cost: 50, val: 180, s: 0, 
      r_th: "⚠️ มีปลาแซลมอนดิบ (Raw/Fish) - ผิดเงื่อนไข", 
      r_en: "⚠️ Contains Raw Fish - Violates constraints.",
      ing_th: "แซลมอนหมักเกลือ, ผักชีลาว, เลมอน, ผักสลัด", ing_en: "Cured Salmon, Dill, Lemon, Salad Greens",
      kcal: 160, protein: "14g", fat: "9g", carbs: "3g" },
    { n: "Caesar Salad", c: "Salad", h: "Calcium (Cheese)", cost: 20, val: 120, s: 1, 
      r_th: "ระวังน้ำสลัดที่มีส่วนผสมของปลาแอนโชวี่ และเบคอน (มัน)", 
      r_en: "Watch out for Anchovy in dressing and fatty bacon.",
      ing_th: "ผักคอส, เบคอนกรอบ, ขนมปังกรอบ, พาเมซานชีส, น้ำสลัดซีซาร์", ing_en: "Cos Lettuce, Crispy Bacon, Croutons, Parmesan, Caesar Dressing",
      kcal: 220, protein: "8g", fat: "18g", carbs: "10g" },

    // APPETIZER
    { n: "Bruschetta Tomato", c: "Appetizer", h: "Lycopene", cost: 15, val: 80, s: 1, 
      r_th: "ทานเล่นได้ 1 ชิ้น มะเขือเทศดีต่อต่อมลูกหมาก แต่หนักแป้ง", 
      r_en: "Good for prostate (Lycopene), but high carb. Limit to 1 pc.",
      ing_th: "ขนมปังบาแก็ต, มะเขือเทศสับ, กระเทียม, โหระพา", ing_en: "Baguette, Chopped Tomatoes, Garlic, Basil",
      kcal: 110, protein: "3g", fat: "4g", carbs: "15g" },
    { n: "French Fries (Plain/Dip)", c: "Appetizer", h: "Carbs, Fat", cost: 10, val: 60, s: 1, 
      r_th: "ตัดกำลังและไขมันสูง เก็บพื้นที่กระเพาะไว้ทานอย่างอื่น", 
      r_en: "High fat filler. Save stomach space for better items.",
      ing_th: "มันฝรั่ง, น้ำมันทอด, เกลือ", ing_en: "Potatoes, Frying Oil, Salt",
      kcal: 300, protein: "3g", fat: "15g", carbs: "40g" },
    { n: "Steamed Mussels (Tomato)", c: "Appetizer", h: "Zinc, Selenium", cost: 45, val: 220, s: 3, 
      r_th: "แหล่ง Zinc ชั้นยอด บำรุงฮอร์โมนชายวัย 50+ ห้ามพลาด", 
      r_en: "Excellent Zinc source for 50+ hormone health. Must try.",
      ing_th: "หอยแมลงภู่, ซอสมะเขือเทศ, ไวน์ขาว, กระเทียม", ing_en: "Mussels, Tomato Sauce, White Wine, Garlic",
      kcal: 140, protein: "12g", fat: "4g", carbs: "8g" },
    { n: "Baked Spinach Cheese", c: "Appetizer", h: "Calcium, Iron", cost: 25, val: 120, s: 2, 
      r_th: "ผักโขมบำรุงสายตา ชีสเสริมแคลเซียม ทานพอประมาณ", 
      r_en: "Spinach for eyes, Cheese for calcium. Eat moderately.",
      ing_th: "ผักโขม, มอสซาเรลล่าชีส, ครีม, กระเทียม", ing_en: "Spinach, Mozzarella Cheese, Cream, Garlic",
      kcal: 250, protein: "10g", fat: "20g", carbs: "5g" },
    { n: "Arancini Parma Ham", c: "Appetizer", h: "Protein, Energy", cost: 35, val: 180, s: 2, 
      r_th: "คุ้มค่าที่พาร์มาแฮมและน้ำมันทรัฟเฟิล อร่อยแต่หนักแป้ง", 
      r_en: "High value Parma Ham & Truffle oil. Delicious but carb-heavy.",
      ing_th: "ข้าวริซอตโต้ทอด, พาร์มาแฮม, ชีส, เกล็ดขนมปัง", ing_en: "Fried Risotto Ball, Parma Ham, Cheese, Breadcrumbs",
      kcal: 280, protein: "8g", fat: "14g", carbs: "30g" },
    { n: "Salmon Ball Spicy Mayo", c: "Appetizer", h: "Protein (Fish)", cost: 20, val: 90, s: 0, 
      r_th: "⚠️ ทำจากปลา (Fish) - ผิดเงื่อนไข", 
      r_en: "⚠️ Made from Fish - Violates constraints.",
      ing_th: "เนื้อปลาแซลมอนบด, แป้ง, ซอสสไปซี่มาโย", ing_en: "Minced Salmon, Flour, Spicy Mayo",
      kcal: 200, protein: "12g", fat: "12g", carbs: "10g" },

    // SOUP
    { n: "Lobster Bisque", c: "Soup", h: "Astaxanthin", cost: 50, val: 250, s: 3, 
      r_th: "ซุปที่แพงที่สุดในร้าน สารต้านอนุมูลอิสระสูงจากเปลือกกุ้ง", 
      r_en: "Most expensive soup. High antioxidants from lobster shells.",
      ing_th: "เปลือกกุ้งล็อบสเตอร์, ครีม, บรั่นดี, ผักคื่นช่ายฝรั่ง", ing_en: "Lobster Shells Stock, Cream, Brandy, Celery",
      kcal: 180, protein: "6g", fat: "14g", carbs: "8g" },
    { n: "Truffle Soup", c: "Soup", h: "Aroma (Relax)", cost: 40, val: 190, s: 2, 
      r_th: "หอมผ่อนคลาย ถ้าชอบกลิ่นทรัฟเฟิลต้องจัด คุ้มกว่าซุปทั่วไป", 
      r_en: "Relaxing aroma. Good value if you love truffle scent.",
      ing_th: "เห็ดทรัฟเฟิลบด, ครีม, น้ำสต็อกเห็ด, น้ำมันทรัฟเฟิล", ing_en: "Truffle Paste, Cream, Mushroom Stock, Truffle Oil",
      kcal: 160, protein: "3g", fat: "12g", carbs: "10g" },
    { n: "Pumpkin & Carrot Soup", c: "Soup", h: "Beta-Carotene", cost: 15, val: 90, s: 2, 
      r_th: "ดีต่อสายตามาก (วิตามินเอสูง) เหมาะกับวัย 50+", 
      r_en: "Great for eyes (High Vit A). Perfect for age 50+.",
      ing_th: "ฟักทองญี่ปุ่น, แครอท, หอมใหญ่, น้ำสต็อกผัก", ing_en: "Japanese Pumpkin, Carrot, Onion, Veggie Stock",
      kcal: 90, protein: "2g", fat: "3g", carbs: "15g" },
    { n: "Tomato Soup", c: "Soup", h: "Lycopene", cost: 15, val: 90, s: 2, 
      r_th: "ดีต่อต่อมลูกหมาก รสเปรี้ยวช่วยกระตุ้นความอยากอาหาร", 
      r_en: "Good for prostate. Sour taste boosts appetite.",
      ing_th: "มะเขือเทศสุก, ใบโหระพา, กระเทียม, น้ำมันมะกอก", ing_en: "Ripe Tomatoes, Basil, Garlic, Olive Oil",
      kcal: 80, protein: "2g", fat: "4g", carbs: "10g" },
    { n: "Potato Cream Soup", c: "Soup", h: "Carbs, Energy", cost: 10, val: 80, s: 1, 
      r_th: "แป้งและครีมธรรมดา ตัดกำลัง ไม่แนะนำ", 
      r_en: "Just starch and cream. A filler, not recommended.",
      ing_th: "มันฝรั่ง, ครีม, เนย, หอมใหญ่", ing_en: "Potato, Cream, Butter, Onion",
      kcal: 200, protein: "4g", fat: "12g", carbs: "20g" },

    // MAIN DISH
    { n: "Aus. Striploin Steak", c: "Main Dish", h: "Protein, Iron", cost: 130, val: 550, s: 0, 
      r_th: "⚠️ เนื้อวัว (Beef) - ผิดเงื่อนไข", 
      r_en: "⚠️ Beef - Violates constraints.",
      ing_th: "เนื้อสันนอกออสเตรเลีย, เกลือ, พริกไทย, เนยสมุนไพร", ing_en: "Australian Striploin, Salt, Pepper, Herb Butter",
      kcal: 350, protein: "35g", fat: "22g", carbs: "0g" },
    { n: "Sea Bass Pumpkin Sauce", c: "Main Dish", h: "Lean Protein", cost: 60, val: 280, s: 0, 
      r_th: "⚠️ ปลา (Fish) - ผิดเงื่อนไข", 
      r_en: "⚠️ Fish - Violates constraints.",
      ing_th: "ปลากะพงย่าง, ซอสฟักทอง, หน่อไม้ฝรั่ง", ing_en: "Grilled Sea Bass, Pumpkin Sauce, Asparagus",
      kcal: 240, protein: "28g", fat: "10g", carbs: "8g" },
    { n: "Smoked Pork Belly (Red Wine)", c: "Main Dish", h: "Protein, Fat", cost: 70, val: 260, s: 2, 
      r_th: "ซอสไวน์แดงทำยาก อร่อยแต่ไขมันสูง ทาน 1-2 ชิ้นพอ", 
      r_en: "Complex sauce. Delicious but high fat. Limit to 1-2 pcs.",
      ing_th: "หมูสามชั้นรมควัน, ซอสไวน์แดง, มันบด", ing_en: "Smoked Pork Belly, Red Wine Sauce, Mashed Potato",
      kcal: 450, protein: "20g", fat: "35g", carbs: "10g" },
    { n: "Steak Cafe de Paris", c: "Main Dish", h: "Protein", cost: 100, val: 450, s: 0, 
      r_th: "⚠️ ส่วนใหญ่เป็นเนื้อวัว (Beef) - ผิดเงื่อนไข", 
      r_en: "⚠️ Beef - Violates constraints.",
      ing_th: "สเต็กเนื้อ, ซอสเนยสมุนไพร Cafe de Paris", ing_en: "Steak, Cafe de Paris Herb Butter Sauce",
      kcal: 400, protein: "30g", fat: "30g", carbs: "2g" },
    { n: "Chicken Roll Parmigiano", c: "Main Dish", h: "Calcium, Protein", cost: 40, val: 190, s: 2, 
      r_th: "เมนูไก่ที่ทำประณีต ซอสชีสให้แคลเซียม ปลอดภัยทานได้", 
      r_en: "Elaborate chicken dish. Cheese sauce adds calcium. Safe.",
      ing_th: "อกไก่ม้วน, ชีสพาร์มิซาน, แฮม, เกล็ดขนมปัง", ing_en: "Rolled Chicken Breast, Parmesan, Ham, Breadcrumbs",
      kcal: 280, protein: "25g", fat: "14g", carbs: "12g" },
    { n: "Salmon Steak", c: "Main Dish", h: "Omega-3", cost: 80, val: 320, s: 0, 
      r_th: "⚠️ ปลา (Fish) - ผิดเงื่อนไข", 
      r_en: "⚠️ Fish - Violates constraints.",
      ing_th: "สเต็กแซลมอน, ซอสครีมมะนาว, ผักย่าง", ing_en: "Salmon Steak, Lemon Cream Sauce, Grilled Veggies",
      kcal: 320, protein: "30g", fat: "20g", carbs: "5g" },
    { n: "Smoked Duck", c: "Main Dish", h: "Iron, Mono-Fat", cost: 50, val: 240, s: 3, 
      r_th: "เป็ดมีธาตุเหล็กสูง ไขมันดีกว่าหมู เนื้อนุ่มเคี้ยวง่าย", 
      r_en: "Higher iron than chicken. Good fats. Soft and easy to chew.",
      ing_th: "อกเป็ดรมควัน, ซอสส้ม, ผักเคียง", ing_en: "Smoked Duck Breast, Orange Sauce, Side Veggies",
      kcal: 220, protein: "18g", fat: "14g", carbs: "6g" },
    { n: "BBQ Pork Ribs", c: "Main Dish", h: "Collagen", cost: 55, val: 280, s: 3, 
      r_th: "คอลลาเจนจากเอ็นข้อต่อช่วยเรื่องเข่า รสเข้มข้น ห้ามพลาด", 
      r_en: "Collagen from joints helps knees. Rich taste. Must try.",
      ing_th: "ซี่โครงหมู, ซอสบาร์บีคิวสูตรพิเศษ, เครื่องเทศ", ing_en: "Pork Ribs, Special BBQ Sauce, Spices",
      kcal: 350, protein: "22g", fat: "20g", carbs: "15g" },
    { n: "Chicken Milanese", c: "Main Dish", h: "Protein, Carbs", cost: 30, val: 160, s: 1, 
      r_th: "ไก่ชุบแป้งทอดธรรมดา เด็กกินได้ผู้ใหญ่กินดี แต่ไม่ว้าว", 
      r_en: "Standard breaded chicken. Okay, but not special.",
      ing_th: "อกไก่, เกล็ดขนมปัง, ไข่, มะนาว", ing_en: "Chicken Breast, Breadcrumbs, Egg, Lemon",
      kcal: 300, protein: "20g", fat: "15g", carbs: "25g" },
    { n: "Mixed Grilled Sausage", c: "Main Dish", h: "Protein, Sodium", cost: 35, val: 180, s: 1, 
      r_th: "ไส้กรอกคุณภาพดี แต่โซเดียมสูง ระวังความดัน", 
      r_en: "Good quality, but high sodium. Watch blood pressure.",
      ing_th: "ไส้กรอกหมู, ไส้กรอกไก่, มัสตาร์ด", ing_en: "Pork Sausage, Chicken Sausage, Mustard",
      kcal: 320, protein: "14g", fat: "28g", carbs: "2g" },

    // SEAFOOD
    { n: "Oysters on Ice", c: "Seafood", h: "Zinc High", cost: 60, val: 300, s: 0, 
      r_th: "⚠️ ของดิบ (Raw) - ผิดเงื่อนไข (เสี่ยงท้องเสีย/พยาธิ)", 
      r_en: "⚠️ Raw Food - Violates constraints (Risk of parasites).",
      ing_th: "หอยนางรมสด, เลมอน, น้ำจิ้มซีฟู้ด", ing_en: "Fresh Oysters, Lemon, Seafood Sauce",
      kcal: 60, protein: "8g", fat: "2g", carbs: "3g" },
    { n: "Mussels on Ice", c: "Seafood", h: "Zinc, B12", cost: 40, val: 250, s: 2, 
      r_th: "ถ้าลวกสุกทานได้ แหล่ง B12 บำรุงเลือด", 
      r_en: "Safe if cooked. B12 source for blood health.",
      ing_th: "หอยแมลงภู่ลวก, น้ำจิ้มซีฟู้ด", ing_en: "Boiled Mussels, Seafood Sauce",
      kcal: 100, protein: "14g", fat: "3g", carbs: "4g" },
    { n: "Shrimp on Ice", c: "Seafood", h: "Astaxanthin", cost: 40, val: 280, s: 2, 
      r_th: "ต้องมั่นใจว่าสุก ถ้าสุกทานได้เลย แคลอรี่ต่ำ โปรตีนสูง", 
      r_en: "Must be cooked. Low calorie, high protein.",
      ing_th: "กุ้งขาวลวก, น้ำจิ้มซีฟู้ด", ing_en: "Boiled White Shrimp, Seafood Sauce",
      kcal: 120, protein: "22g", fat: "1g", carbs: "0g" },

    // PIZZA
    { n: "Margherita Pizza", c: "Pizza", h: "Lycopene", cost: 15, val: 120, s: 1, 
      r_th: "เบสิกเกินไป แป้งเยอะ ตัดกำลัง", 
      r_en: "Too basic. Too much dough. A filler.",
      ing_th: "แป้งพิซซ่า, ซอสมะเขือเทศ, มอสซาเรลล่าชีส, โหระพา", ing_en: "Dough, Tomato Sauce, Mozzarella, Basil",
      kcal: 250, protein: "10g", fat: "8g", carbs: "35g" },
    { n: "Diavola Pizza", c: "Pizza", h: "Capsaicin (Chili)", cost: 20, val: 150, s: 2, 
      r_th: "รสเผ็ดช่วยกระตุ้นการเผาผลาญ แก้เลี่ยนได้ดี", 
      r_en: "Spicy taste boosts metabolism and cuts grease.",
      ing_th: "ซาลามี่รสเผ็ด, พริกสด, ชีส, ซอสมะเขือเทศ", ing_en: "Spicy Salami, Fresh Chili, Cheese, Tomato Sauce",
      kcal: 280, protein: "12g", fat: "14g", carbs: "32g" },
    { n: "Formaggi Pizza", c: "Pizza", h: "Calcium High", cost: 30, val: 180, s: 2, 
      r_th: "สำหรับคนรักชีส แคลเซียมสูงมาก แต่เค็ม (Sodium)", 
      r_en: "For cheese lovers. High Calcium, but high Sodium.",
      ing_th: "กอร์กอนโซล่า, มอสซาเรลล่า, พาร์มิซาน, ฟอนติน่า", ing_en: "Gorgonzola, Mozzarella, Parmesan, Fontina",
      kcal: 320, protein: "15g", fat: "18g", carbs: "30g" },
    { n: "Salmon Spinach Calzone", c: "Pizza", h: "Omega-3", cost: 35, val: 190, s: 0, 
      r_th: "⚠️ มีแซลมอน (Fish) - ผิดเงื่อนไข", 
      r_en: "⚠️ Contains Salmon - Violates constraints.",
      ing_th: "แป้งพับ, แซลมอน, ผักโขม, ชีส", ing_en: "Folded Dough, Salmon, Spinach, Cheese",
      kcal: 350, protein: "18g", fat: "15g", carbs: "40g" },
    { n: "Mixed Mushroom Pizza", c: "Pizza", h: "Fiber", cost: 20, val: 140, s: 1, 
      r_th: "ธรรมดาไปหน่อย ถ้าจะกินเห็ดไปกินซุปทรัฟเฟิลดีกว่า", 
      r_en: "Average. Better to get mushroom fix from Truffle Soup.",
      ing_th: "เห็ดแชมปิญอง, เห็ดหอม, ชีส, น้ำมันทรัฟเฟิล", ing_en: "Champignon, Shiitake, Cheese, Truffle Oil",
      kcal: 240, protein: "8g", fat: "10g", carbs: "32g" },
    { n: "Truffle Cream Pizza", c: "Pizza", h: "Aroma", cost: 35, val: 220, s: 3, 
      r_th: "แป้งพิซซ่าที่คุ้มที่สุดในร้านคือหน้านี้ หอมทรัฟเฟิลมาก", 
      r_en: "Best value pizza here. Very aromatic truffle.",
      ing_th: "ซอสครีมทรัฟเฟิล, เห็ดทรัฟเฟิลสไลซ์, ชีส", ing_en: "Truffle Cream Sauce, Sliced Truffle, Cheese",
      kcal: 290, protein: "10g", fat: "15g", carbs: "30g" },

    // PASTA
    { n: "Ham & Mushroom Penne", c: "Pasta", h: "Energy", cost: 25, val: 160, s: 1, 
      r_th: "ครีมซอสหนักไป อาจทำให้อิ่มเร็ว", 
      r_en: "Heavy cream sauce. Might fill you up too fast.",
      ing_th: "เส้นเพนเน่, แฮม, เห็ด, ครีมซอส", ing_en: "Penne, Ham, Mushroom, Cream Sauce",
      kcal: 350, protein: "12g", fat: "18g", carbs: "45g" },
    { n: "Capellini AOP Bacon", c: "Pasta", h: "Energy", cost: 20, val: 150, s: 1, 
      r_th: "ผัดพริกแห้งตัดเลี่ยนได้ แต่ต้นทุนต่ำ", 
      r_en: "Spicy oil cuts grease, but low ingredient cost.",
      ing_th: "เส้นแองเจิลแฮร์, เบคอน, พริกแห้ง, กระเทียม", ing_en: "Angel Hair, Bacon, Dried Chili, Garlic",
      kcal: 320, protein: "10g", fat: "16g", carbs: "40g" },
    { n: "Capellini AOP Shrimp", c: "Pasta", h: "Protein", cost: 30, val: 180, s: 2, 
      r_th: "กุ้งผัดพริกแห้ง ทานง่าย ไม่เลี่ยน", 
      r_en: "Shrimp with spicy oil. Easy to eat, not greasy.",
      ing_th: "เส้นแองเจิลแฮร์, กุ้ง, พริกแห้ง, น้ำมันมะกอก", ing_en: "Angel Hair, Shrimp, Dried Chili, Olive Oil",
      kcal: 280, protein: "18g", fat: "8g", carbs: "40g" },
    { n: "Linguine Vongole", c: "Pasta", h: "Iron (Clams)", cost: 35, val: 220, s: 3, 
      r_th: "หอยลายผัดไวน์ขาว รสชาติดี ธาตุเหล็กสูง แนะนำ!", 
      r_en: "Clams in white wine. Tasty & High Iron. Recommended!",
      ing_th: "เส้นลิงกวินี่, หอยลาย, ไวน์ขาว, ใบโหระพา", ing_en: "Linguine, Clams, White Wine, Basil",
      kcal: 300, protein: "15g", fat: "8g", carbs: "42g" },
    { n: "Rigatoni Puttanesca", c: "Pasta", h: "Lycopene", cost: 25, val: 160, s: 2, 
      r_th: "ซอสมะเขือเทศรสจัดจ้าน ระวังส่วนผสมแอนโชวี่ (ถามร้าน)", 
      r_en: "Zesty tomato sauce. Check for Anchovies (Fish).",
      ing_th: "เส้นริกาโตนี, มะกอกดำ, เคเปอร์, ซอสมะเขือเทศ", ing_en: "Rigatoni, Black Olives, Capers, Tomato Sauce",
      kcal: 260, protein: "8g", fat: "10g", carbs: "40g" },
    { n: "Rigatoni Seafood", c: "Pasta", h: "Protein Mix", cost: 40, val: 240, s: 3, 
      r_th: "รวมมิตรทะเล (กุ้ง/หมึก) คุ้มค่ามาก ทานเครื่องทิ้งเส้น", 
      r_en: "Seafood mix (Shrimp/Squid). Great value. Eat toppings, skip pasta.",
      ing_th: "เส้นริกาโตนี, กุ้ง, ปลาหมึก, หอย, ซอสมะเขือเทศ", ing_en: "Rigatoni, Shrimp, Squid, Shellfish, Tomato Sauce",
      kcal: 320, protein: "20g", fat: "8g", carbs: "42g" },
    { n: "Capellini AOP Beef", c: "Pasta", h: "Protein", cost: 40, val: 200, s: 0, 
      r_th: "⚠️ เนื้อวัว (Beef) - ผิดเงื่อนไข", 
      r_en: "⚠️ Beef - Violates constraints.",
      ing_th: "เส้นแองเจิลแฮร์, เนื้อวัวชิ้น, พริกแห้ง", ing_en: "Angel Hair, Beef Slices, Dried Chili",
      kcal: 350, protein: "20g", fat: "15g", carbs: "40g" },
    { n: "Spaghetti Carbonara", c: "Pasta", h: "Energy", cost: 30, val: 180, s: 1, 
      r_th: "อ้วนและเลี่ยน ตัดกำลังสุดๆ ถ้าไม่ชอบจริงๆ ข้ามไป", 
      r_en: "Fattening and heavy. A major filler. Skip it.",
      ing_th: "สปาเก็ตตี้, ไข่แดง, ชีส, เบคอน, ครีม", ing_en: "Spaghetti, Egg Yolk, Cheese, Bacon, Cream",
      kcal: 450, protein: "15g", fat: "25g", carbs: "45g" },
    { n: "Fettuccine Truffle", c: "Pasta", h: "Aroma", cost: 40, val: 240, s: 2, 
      r_th: "อร่อยหรูหรา แต่ระวังเลี่ยนครีม ทานนิดเดียวพอ", 
      r_en: "Luxurious taste, but creamy. Eat a small portion.",
      ing_th: "เส้นเฟตตูชินี, ครีมทรัฟเฟิล, เห็ด, ชีส", ing_en: "Fettuccine, Truffle Cream, Mushroom, Cheese",
      kcal: 380, protein: "10g", fat: "20g", carbs: "42g" },
    { n: "Seafood Pesto", c: "Pasta", h: "Herbs", cost: 35, val: 200, s: 2, 
      r_th: "ซอสโหระพาหอมสดชื่น ดีต่อสุขภาพกว่าซอสครีม", 
      r_en: "Fresh basil sauce. Healthier than cream sauce.",
      ing_th: "เส้นพาสต้า, กุ้ง, ปลาหมึก, ซอสเพสโต้ (โหระพา/ถั่ว)", ing_en: "Pasta, Shrimp, Squid, Pesto Sauce (Basil/Nuts)",
      kcal: 340, protein: "18g", fat: "16g", carbs: "40g" },

    // DESSERT
    { n: "Cheesecake", c: "Dessert", h: "Calcium, Fat", cost: 25, val: 120, s: 2, 
      r_th: "อร่อยมาตรฐาน แคลเซียมสูง", 
      r_en: "Standard taste. High Calcium.",
      ing_th: "ครีมชีส, แครกเกอร์, เนย, น้ำตาล", ing_en: "Cream Cheese, Cracker Base, Butter, Sugar",
      kcal: 320, protein: "6g", fat: "22g", carbs: "25g" },
    { n: "Avocado Panna Cotta", c: "Dessert", h: "Healthy Fats", cost: 30, val: 140, s: 3, 
      r_th: "หาทานยาก ใช้ไขมันดีจากอะโวคาโดทำขนม หวานน้อย", 
      r_en: "Rare find. Healthy fats from Avocado. Low sugar.",
      ing_th: "อะโวคาโด, วิปครีม, เจลาติน, นม", ing_en: "Avocado, Heavy Cream, Gelatin, Milk",
      kcal: 220, protein: "4g", fat: "18g", carbs: "12g" },
    { n: "Chocolate Mousse", c: "Dessert", h: "Antioxidant", cost: 25, val: 120, s: 2, 
      r_th: "ถ้าเป็น Dark Choc จะดีต่อหัวใจ ทานได้", 
      r_en: "If Dark Choc, good for heart. Acceptable.",
      ing_th: "ดาร์กช็อกโกแลต, ไข่ขาว, ครีม", ing_en: "Dark Chocolate, Egg Whites, Cream",
      kcal: 250, protein: "5g", fat: "15g", carbs: "20g" },
    { n: "Apple Mousse Crumble", c: "Dessert", h: "Fruit Fiber", cost: 25, val: 130, s: 2, 
      r_th: "สดชื่น มีเนื้อผลไม้", 
      r_en: "Refreshing with real fruit bits.",
      ing_th: "แอปเปิ้ลเขียว, ครัมเบิ้ลเนย, มูสวานิลลา", ing_en: "Green Apple, Butter Crumble, Vanilla Mousse",
      kcal: 200, protein: "3g", fat: "10g", carbs: "28g" },
    { n: "Strawberry Cheesecake Ice Cream", c: "Dessert", h: "Sugar", cost: 20, val: 80, s: 1, 
      r_th: "หวานเย็นธรรมดา", 
      r_en: "Just sweet ice cream.",
      ing_th: "นม, สตรอเบอร์รี่ไซรัป, ชิ้นชีสเค้ก", ing_en: "Milk, Strawberry Syrup, Cheesecake Bits",
      kcal: 180, protein: "3g", fat: "8g", carbs: "25g" },
    { n: "Cookie & Cream Ice Cream", c: "Dessert", h: "Sugar", cost: 20, val: 80, s: 1, 
      r_th: "เด็กชอบ ผู้ใหญ่ระวังน้ำตาล", 
      r_en: "Kids love it. Watch sugar levels.",
      ing_th: "นม, คุกกี้โอรีโอ้, น้ำตาล", ing_en: "Milk, Oreo Cookies, Sugar",
      kcal: 200, protein: "3g", fat: "10g", carbs: "28g" },
    { n: "Vanilla Macadamia Ice Cream", c: "Dessert", h: "Nut Oils", cost: 35, val: 120, s: 3, 
      r_th: "แมคคาเดเมียแพงและอร่อย ไขมันดีจากถั่ว", 
      r_en: "Expensive Macadamia nuts. Good fats.",
      ing_th: "วานิลลาแท้, ถั่วแมคคาเดเมีย, นม", ing_en: "Real Vanilla, Macadamia Nuts, Milk",
      kcal: 240, protein: "4g", fat: "16g", carbs: "20g" },
    { n: "Red Berry Sorbet", c: "Dessert", h: "Vit C, No Fat", cost: 25, val: 90, s: 3, 
      r_th: "ล้างปากดีที่สุด ไม่มีไขมัน สดชื่นตื่นตัว", 
      r_en: "Best palate cleanser. Fat-free and refreshing.",
      ing_th: "ราสเบอร์รี่, สตรอเบอร์รี่, น้ำมะนาว", ing_en: "Raspberry, Strawberry, Lemon Juice",
      kcal: 100, protein: "0g", fat: "0g", carbs: "25g" },
    { n: "Chocolate Lava", c: "Dessert", h: "Antioxidant", cost: 40, val: 160, s: 2, 
      r_th: "อร่อยแต่หวานจัด แบ่งกันทานจะดี", 
      r_en: "Delicious but very sweet. Share it.",
      ing_th: "ช็อกโกแลต, เนย, ไข่, แป้ง", ing_en: "Chocolate, Butter, Eggs, Flour",
      kcal: 350, protein: "6g", fat: "22g", carbs: "35g" },
    { n: "Creme Brulee", c: "Dessert", h: "Protein, Fat", cost: 25, val: 120, s: 2, 
      r_th: "คัสตาร์ดเนื้อเนียน น้ำตาลไหม้หอมๆ", 
      r_en: "Smooth custard with burnt sugar aroma.",
      ing_th: "ไข่แดง, วิปครีม, วานิลลา, น้ำตาลทรายแดง", ing_en: "Egg Yolks, Heavy Cream, Vanilla, Brown Sugar",
      kcal: 300, protein: "5g", fat: "25g", carbs: "15g" },
    { n: "Mille-Feuille", c: "Dessert", h: "Skill Value", cost: 35, val: 180, s: 3, 
      r_th: "ขนมปราบเซียน ทำยากมาก ต้องลองให้รู้รส", 
      r_en: "High technique pastry. Hard to make. Must try.",
      ing_th: "แป้งพายชั้น, ครีมวานิลลา, น้ำตาลไอซิ่ง", ing_en: "Puff Pastry, Vanilla Cream, Icing Sugar",
      kcal: 280, protein: "4g", fat: "18g", carbs: "26g" },
    { n: "Tiramisu", c: "Dessert", h: "Caffeine", cost: 35, val: 160, s: 3, 
      r_th: "ใช้ชีส Mascarpone แพง หอมกาแฟช่วยย่อย", 
      r_en: "Uses expensive Mascarpone. Coffee aids digestion.",
      ing_th: "ชีสมาสคาร์โปเน่, กาแฟเอสเพรสโซ, เลดี้ฟิงเกอร์, โกโก้", ing_en: "Mascarpone, Espresso, Ladyfingers, Cocoa",
      kcal: 300, protein: "6g", fat: "20g", carbs: "24g" }
];

export const beverageDB: MenuItem[] = [
    // Soft Drinks
    { n: "Chang Drinking Water", c: "Soft Drinks", h: "Hydration", cost: 5, val: 20, s: 3,
      r_th: "ดื่มเพื่อล้างรสชาติระหว่างจาน ดีที่สุด", r_en: "Best for palate cleansing between courses.",
      ing_th: "น้ำแร่ธรรมชาติ", ing_en: "Natural Mineral Water",
      kcal: 0, protein: "0g", fat: "0g", carbs: "0g", sugar: "0g" },
    { n: "Est-Cola", c: "Soft Drinks", h: "Sugar Rush", cost: 10, val: 40, s: 0,
      r_th: "น้ำตาลสูงมาก ตัดกำลัง ทำให้อิ่มเร็ว ควรเลี่ยง", r_en: "High sugar filler. Makes you full fast. Avoid.",
      ing_th: "น้ำตาล, คาเฟอีน, คาราเมล", ing_en: "Sugar, Caffeine, Caramel",
      kcal: 140, protein: "0g", fat: "0g", carbs: "36g", sugar: "36g" },
    { n: "Est-Cola Sugar Free", c: "Soft Drinks", h: "No Sugar", cost: 10, val: 40, s: 2,
      r_th: "ทางเลือกถ้าอยากดื่มน้ำอัดลม ไม่มีน้ำตาล", r_en: "Alternative if you crave soda. No sugar.",
      ing_th: "สารให้ความหวานแทนน้ำตาล, คาเฟอีน", ing_en: "Sweetener, Caffeine",
      kcal: 0, protein: "0g", fat: "0g", carbs: "0g", sugar: "0g" },
    { n: "Schweppes Ginger Ale", c: "Soft Drinks", h: "Digestion", cost: 15, val: 50, s: 2,
      r_th: "ช่วยขับลม แก้ท้องอืดได้ดี", r_en: "Helps with digestion and bloating.",
      ing_th: "ขิง, น้ำตาล, โซดา", ing_en: "Ginger, Sugar, Soda",
      kcal: 120, protein: "0g", fat: "0g", carbs: "30g", sugar: "28g" },
    
    // Mocktails
    { n: "VP Sling", c: "Mocktails", h: "Refreshing", cost: 20, val: 120, s: 2,
      r_th: "เปรี้ยวหวานสดชื่น แต่มีน้ำตาลผลไม้", r_en: "Sweet & Sour refreshing. Contains fruit sugar.",
      ing_th: "น้ำสับปะรด, น้ำมะนาว, น้ำเชื่อมทับทิม", ing_en: "Pineapple Juice, Lime Juice, Grenadine",
      kcal: 150, protein: "0g", fat: "0g", carbs: "38g", sugar: "35g" },
    { n: "Green Floral", c: "Mocktails", h: "Aromatic", cost: 20, val: 120, s: 2,
      r_th: "หอมกลิ่นดอกไม้ ดื่มง่าย", r_en: "Floral aroma. Easy to drink.",
      ing_th: "ไซรัปดอกไม้, โซดา, มะนาว", ing_en: "Floral Syrup, Soda, Lime",
      kcal: 110, protein: "0g", fat: "0g", carbs: "28g", sugar: "28g" },
    
    // Coffee
    { n: "Espresso", c: "Coffee (Hot Only)", h: "Caffeine", cost: 15, val: 60, s: 3,
      r_th: "แนะนำปิดท้ายมื้อ ช่วยย่อยและเผาผลาญ", r_en: "Recommended to finish the meal. Aids metabolism.",
      ing_th: "เมล็ดกาแฟอาราบิก้าคั่ว", ing_en: "Roasted Arabica Coffee Beans",
      kcal: 5, protein: "0g", fat: "0g", carbs: "1g", sugar: "0g" },
    { n: "Americano", c: "Coffee (Hot Only)", h: "Low Calorie", cost: 15, val: 70, s: 3,
      r_th: "กาแฟดำ ดีต่อสุขภาพ ไม่มีไขมัน", r_en: "Black coffee. Healthy. No fat.",
      ing_th: "เอสเพรสโซ, น้ำร้อน", ing_en: "Espresso, Hot Water",
      kcal: 5, protein: "0g", fat: "0g", carbs: "1g", sugar: "0g" },
    { n: "Cappuccino", c: "Coffee (Hot Only)", h: "Milk Foam", cost: 20, val: 80, s: 2,
      r_th: "มีนมนิดหน่อย พอให้ลื่นคอ", r_en: "A bit of milk for smoothness.",
      ing_th: "เอสเพรสโซ, นมร้อน, ฟองนม", ing_en: "Espresso, Steamed Milk, Foam",
      kcal: 80, protein: "4g", fat: "3g", carbs: "8g", sugar: "4g" },
      
    // Special
    { n: "Chang Cold Brew", c: "Special Drink", h: "Malt Aroma", cost: 25, val: 120, s: 3,
      r_th: "เบียร์สกัดเย็น นุ่มลื่น ล้างไขมันในปากได้ดี", r_en: "Cold brew lager. Smooth. Cleanses palate fat.",
      ing_th: "ข้าวมอลต์, ฮอปส์, น้ำแร่", ing_en: "Malt, Hops, Mineral Water",
      kcal: 130, protein: "1g", fat: "0g", carbs: "12g", sugar: "0g" }
];