
import { MenuItem, Translations, DietaryStyle } from './types';

export const translations: Translations = {
    th: {
        app_title: "VP Buffet Strategist",
        app_subtitle: "วางแผนการกินบุฟเฟต์อย่างชาญฉลาด",
        diet_selector: "รูปแบบการกิน:",
        diet_omni: "ทั่วไป (เน้นคุ้ม)",
        diet_keto: "คีโต (ไขมัน/โปรตีน)",
        diet_veg: "มังสวิรัติ (Plant-Based)",
        diet_pesc: "เพสคาทาเรียน (เน้นปลา)",
        nav_dash: "แดชบอร์ด & แผนกลยุทธ์",
        nav_menu: "เจาะลึกเมนูอาหาร",
        nav_bev: "เครื่องดื่ม",
        nav_dash_short: "แผนกลยุทธ์",
        nav_menu_short: "เมนู",
        nav_bev_short: "เครื่องดื่ม",
        filter_all: "ทั้งหมด",
        filter_rec: "แนะนำ",
        filter_avoid: "ควรเลี่ยง",
        cat_all: "ทุกหมวดหมู่",
        th_menu: "เมนูอาหาร",
        th_cat: "หมวดหมู่",
        th_key: "จุดเด่น",
        th_val: "มูลค่าตลาด",
        th_status: "สถานะ",
        click_hint: "คลิกที่แถวเพื่อดูส่วนผสมและโภชนาการอย่างละเอียด",
        modal_ing: "ส่วนประกอบหลัก",
        modal_nutri_grid: "ข้อมูลโภชนาการ (โดยประมาณ)",
        modal_nutri_highlight: "จุดเด่นทางโภชนาการ",
        modal_cost: "ต้นทุน (ครึ่งจาน)",
        modal_cost_sub: "ประมาณการต้นทุน",
        modal_val: "มูลค่าตลาด",
        modal_val_sub: "ราคาหน้าร้านทั่วไป",
        modal_advice: "คำแนะนำทางโภชนาการ",
        modal_close: "เข้าใจแล้ว",
        about_title: "ยินดีต้อนรับสู่ VP Buffet Strategist",
        about_sub: "European Mercantile Concept",
        about_atmosphere: "บรรยากาศและคอนเซปต์",
        about_atm_desc: "Vantage Point (QSNCC) นำเสนอประสบการณ์แบบ <strong>\"European Mercantile\"</strong> ที่ผสานความหรูหราเข้ากับความมีชีวิตชีวาของตลาดอาหารยุโรป จุดเด่นสำคัญคือรูปแบบ <strong>\"A La Carte Buffet\"</strong> อาหารทุกจานปรุงสดใหม่ (Made-to-order) ทำให้ได้คุณภาพระดับภัตตาคาร",
        about_logic: "หลักการ Strategic Eating",
        about_logic_desc: "ระบบของเราไม่ได้แค่แนะนำเมนู แต่ช่วย <strong>\"วางลำดับการกิน\"</strong> เพื่อให้ร่างกายดูดซึมสารอาหารได้ดีที่สุดและคุ้มค่าที่สุด เราคำนวณ Macro/Micronutrients ตามรูปแบบการกินที่คุณเลือก (Dietary Style) เพื่อให้คุณอิ่มอร่อยโดยไม่รู้สึกผิด",
        stat_total: "รายการอาหารทั้งหมด",
        stat_safe: "เมนูที่ตรงโจทย์คุณ",
        stat_value: "มูลค่าที่ทานได้จริง",
        stat_avoid: "เมนูที่ควรเลี่ยง",
        plan_title: "แผนการกินแนะนำ (ตามรูปแบบที่คุณเลือก)",
        plan_name_1: "The Generalist (สายคุ้มค่า)",
        plan_why_1: "เน้นเมนูที่มูลค่าตลาดสูงสุด (ROI) วัตถุดิบพรีเมียม และรสชาติที่หลากหลาย เหมาะสำหรับคนทานได้ทุกอย่าง",
        plan_name_2: "Keto Warrior (สายคีโต)",
        plan_why_2: "ตัดแป้งและน้ำตาล เน้นโปรตีนและไขมันดี รักษาภาวะ Ketosis ด้วยสเต็กและชีสคุณภาพสูง",
        plan_name_3: "Green Strategist (สายผัก)",
        plan_why_3: "โฟกัสที่ไฟเบอร์ วิตามิน และโปรตีนจากพืช ตัดเนื้อสัตว์ทุกชนิด แต่ยังคงความอร่อยแบบพรีเมียม",
        plan_name_4: "Ocean & Earth (สายปลา)",
        plan_why_4: "เน้นอาหารทะเลและพืชผัก ได้รับ Omega-3 สูง ย่อยง่าย และไขมันอิ่มตัวต่ำ",
        step1_t: "Warm Up", step1_d: "ช่วงเตรียมพร้อม",
        step2_t: "Green & Light", step2_d: "ช่วงเติมไฟเบอร์",
        step3_t: "Main Event", step3_d: "จานหลักตามเป้าหมาย",
        step4_t: "Second Wave", step4_d: "ชิมรสชาติที่หลากหลาย",
        step5_t: "Closing", step5_d: "ช่วงล้างปากช่วยย่อย",
        bev_advice_title: "คำแนะนำการดื่ม",
        bev_advice_desc: "เพื่อความคุ้มค่าและสุขภาพ: <span class='font-semibold bg-amber-100 px-1'>เลี่ยงน้ำหวาน/อัดลม</span> หากต้องการตัดกำลัง, เน้น <span class='font-semibold bg-amber-100 px-1'>Chang Cold Brew</span> หรือ <span class='font-semibold bg-amber-100 px-1'>Sparkling Water</span> เพื่อล้างลิ้น และปิดท้ายด้วย <span class='font-semibold bg-amber-100 px-1'>กาแฟร้อน</span> เพื่อช่วยย่อย",
        bev_soft: "Soft Drinks",
        bev_mock: "Mocktails",
        bev_coffee: "Coffee (Hot Only)",
        bev_spec: "Special Drink",
        nutri_cal: "พลังงาน",
        nutri_prot: "โปรตีน",
        nutri_fat: "ไขมัน",
        nutri_carb: "คาร์บ",
        nutri_sugar: "น้ำตาล"
    },
    en: {
        app_title: "VP Buffet Strategist",
        app_subtitle: "Strategic Dining Intelligence",
        diet_selector: "Diet Style:",
        diet_omni: "Omnivore (Value)",
        diet_keto: "Keto (Low Carb)",
        diet_veg: "Vegetarian",
        diet_pesc: "Pescatarian",
        nav_dash: "Dashboard & Strategy",
        nav_menu: "Menu Intelligence",
        nav_bev: "Beverages",
        nav_dash_short: "Strategy",
        nav_menu_short: "Menu",
        nav_bev_short: "Drinks",
        filter_all: "All",
        filter_rec: "Recommended",
        filter_avoid: "Avoid",
        cat_all: "All Categories",
        th_menu: "Menu Item",
        th_cat: "Category",
        th_key: "Highlight",
        th_val: "Market Value",
        th_status: "Suitability",
        click_hint: "Click row for detailed ingredients & nutrients",
        modal_ing: "Main Ingredients",
        modal_nutri_grid: "Nutrition Facts (Est.)",
        modal_nutri_highlight: "Nutritional Highlight",
        modal_cost: "Cost (Half Portion)",
        modal_cost_sub: "Estimated Cost",
        modal_val: "Market Value",
        modal_val_sub: "A La Carte Price",
        modal_advice: "Nutritional Verdict",
        modal_close: "Close",
        about_title: "Welcome to VP Buffet Strategist",
        about_sub: "European Mercantile Concept",
        about_atmosphere: "Atmosphere & Concept",
        about_atm_desc: "Vantage Point (QSNCC) offers a <strong>\"European Mercantile\"</strong> experience, blending luxury with the liveliness of European food markets. Featuring an <strong>\"A La Carte Buffet\"</strong> style, every dish is <em>\"Made-to-order\"</em>, ensuring restaurant-quality freshness.",
        about_logic: "The Strategic Eating Logic",
        about_logic_desc: "We don't just list food; we <strong>\"Sequence\"</strong> it. Our algorithm calculates the optimal eating order to maximize nutrient absorption and value based on your chosen <strong>Dietary Style</strong>, ensuring you leave satisfied, not stuffed.",
        stat_total: "Total Items",
        stat_safe: "Matches Your Diet",
        stat_value: "Market Value",
        stat_avoid: "Avoid (Restricted)",
        plan_title: "Recommended Strategy (Based on your Diet)",
        plan_name_1: "The Generalist (Max ROI)",
        plan_why_1: "Targets maximum Return on Investment (ROI) by focusing on high-cost ingredients and variety. No restrictions.",
        plan_name_2: "Keto Warrior",
        plan_why_2: "Eliminates carbs and sugar. Prioritizes premium fats and proteins to maintain Ketosis while dining luxuriously.",
        plan_name_3: "Green Strategist",
        plan_why_3: "Focuses on fiber, vitamins, and plant-based proteins. Completely eliminates meat while maximizing flavor.",
        plan_name_4: "Ocean & Earth",
        plan_why_4: "A Pescatarian approach. High Omega-3 from seafood paired with nutrient-dense vegetables. Light and energetic.",
        step1_t: "Warm Up", step1_d: "Preparation Phase",
        step2_t: "Green & Light", step2_d: "Fiber Loading",
        step3_t: "Main Event", step3_d: "Target Macros",
        step4_t: "Second Wave", step4_d: "Taste Exploration",
        step5_t: "Closing", step5_d: "Digestif Phase",
        bev_advice_title: "Drinking Strategy",
        bev_advice_desc: "For value & health: <span class='font-semibold bg-amber-100 px-1'>Skip Sugary Sodas</span>. Focus on <span class='font-semibold bg-amber-100 px-1'>Chang Cold Brew</span> or <span class='font-semibold bg-amber-100 px-1'>Sparkling Water</span> to cleanse palate. Finish with <span class='font-semibold bg-amber-100 px-1'>Hot Coffee</span> to aid digestion.",
        bev_soft: "Soft Drinks",
        bev_mock: "Mocktails",
        bev_coffee: "Coffee (Hot Only)",
        bev_spec: "Special Drink",
        nutri_cal: "Calories",
        nutri_prot: "Protein",
        nutri_fat: "Fat",
        nutri_carb: "Carbs",
        nutri_sugar: "Sugar"
    }
};

export const menuDB: MenuItem[] = [
    // --- SALAD ---
    { n: "Baby Kale Salad", c: "Salad", h: "Vitamin K, Fiber", cost: 25, val: 120, tags: ['veg', 'premium'],
      r_th: "Kale คือ Superfood ช่วยระบบขับถ่ายและบำรุงกระดูก", 
      r_en: "Kale is a Superfood, aiding digestion and bone health.",
      ing_th: "เบบี้เคล, น้ำสลัดเลมอน, น้ำมันมะกอก, พาเมซานชีส, ถั่ววอลนัทอบ", ing_en: "Baby Kale, Lemon Vinaigrette, Extra Virgin Olive Oil, Aged Parmesan, Roasted Walnuts",
      kcal: 85, protein: "3g", fat: "6g", carbs: "5g", sugar: "1g" },
    { n: "Avocado & Orange Salad", c: "Salad", h: "Healthy Fats, Vit C", cost: 35, val: 160, tags: ['veg', 'premium', 'high_fat'],
      r_th: "เมนูสุขภาพอันดับ 1 ไขมันดีลดคอเลสเตอรอล", 
      r_en: "#1 Healthy Choice. Good fats reduce cholesterol.",
      ing_th: "อะโวคาโด, เนื้อส้ม, ผักสลัดโอ๊ค, ซอสบัลซามิก, ถั่วพิสตาชิโอ", ing_en: "Fresh Avocado, Orange Segments, Mixed Oak Lettuce, Balsamic Glaze, Pistachio Nuts",
      kcal: 140, protein: "2g", fat: "12g", carbs: "10g", sugar: "6g" },
    { n: "Shrimp Salad", c: "Salad", h: "Lean Protein", cost: 40, val: 150, tags: ['seafood'],
      r_th: "กุ้งเป็นแหล่งโปรตีนที่ดี น้ำสลัดครีมอาจอ้วนได้", 
      r_en: "Shrimp is great lean protein. Watch the dressing.",
      ing_th: "กุ้งขาวลวก, ผักคอส, ผักกาดแก้ว, มะเขือเทศราชินี, น้ำสลัดครีมงา", ing_en: "Boiled White Shrimp, Cos Lettuce, Iceberg Lettuce, Cherry Tomatoes, Creamy Sesame Dressing",
      kcal: 180, protein: "15g", fat: "10g", carbs: "6g", sugar: "3g" },
    { n: "Quinoa Salad", c: "Salad", h: "Complete Protein", cost: 20, val: 140, tags: ['veg', 'carb'],
      r_th: "ควินัวให้โปรตีนและไฟเบอร์สูงมาก อิ่มท้อง", 
      r_en: "Quinoa offers high protein & fiber. Filling.",
      ing_th: "ควินัว 3 สี, แตงกวาญี่ปุ่น, พริกหวานแดง/เหลือง, หอมแดง, น้ำมันมะกอก", ing_en: "Tricolor Quinoa, Japanese Cucumber, Bell Peppers, Red Onion, Extra Virgin Olive Oil",
      kcal: 120, protein: "5g", fat: "4g", carbs: "18g", sugar: "2g" },
    { n: "Salmon Gravlax Salad", c: "Salad", h: "Omega-3", cost: 50, val: 180, tags: ['seafood', 'raw', 'premium'],
      r_th: "แซลมอนหมักเกลือ โปรตีนสูง โอเมก้า 3 สูง", 
      r_en: "Cured salmon is rich in Protein and Omega-3.",
      ing_th: "แซลมอนหมักเกลือ/น้ำตาล, ผักชีลาว, ผิวเลมอน, ผักสลัดรวม, เคเปอร์", ing_en: "Cured Salmon (Salt/Sugar), Fresh Dill, Lemon Zest, Mixed Salad Greens, Capers",
      kcal: 160, protein: "14g", fat: "9g", carbs: "3g", sugar: "2g" },
    { n: "Caesar Salad", c: "Salad", h: "Calcium (Cheese)", cost: 20, val: 120, tags: ['pork', 'seafood', 'high_fat'],
      r_th: "ระวังน้ำสลัดที่มีส่วนผสมของปลาแอนโชวี่ และเบคอน", 
      r_en: "Contains Anchovy in dressing and fatty bacon.",
      ing_th: "ผักคอส, เบคอนกรอบ, ขนมปังกรอบกระเทียม, พาเมซานชีสแผ่น, น้ำสลัดซีซาร์", ing_en: "Cos Lettuce, Crispy Bacon Bits, Garlic Croutons, Shaved Parmesan, Caesar Dressing",
      kcal: 220, protein: "8g", fat: "18g", carbs: "10g", sugar: "2g" },

    // --- APPETIZER ---
    { n: "Mixed Fries with Triple Dipping Sauce", c: "Appetizer", h: "Variety", cost: 15, val: 90, tags: ['carb', 'high_fat', 'fried', 'veg'],
      r_th: "รวมมิตรมันฝรั่งทอด 3 แบบ ตัดกำลัง", r_en: "Mix of 3 fries types. High carb/fat.",
      ing_th: "มันฝรั่งเส้นเล็ก, เคอร์ลี่ฟรายส์, มันฝรั่งชิ้นใหญ่, ดิป 3 ชนิด", ing_en: "Shoestring Fries, Curly Fries, Wedges, Triple Dip (Mayo/Ketchup/Cheese)",
      kcal: 350, protein: "4g", fat: "18g", carbs: "45g", sugar: "3g" },
    { n: "Bruschetta Tomato", c: "Appetizer", h: "Lycopene", cost: 15, val: 80, tags: ['veg', 'carb'],
      r_th: "มะเขือเทศสดชื่น แต่หนักแป้งจากขนมปัง", r_en: "Refreshing tomato, but high carb base.",
      ing_th: "ขนมปังบาแก็ต, มะเขือเทศสับ, กระเทียม, โหระพา, น้ำมันมะกอก", ing_en: "Baguette, Diced Tomato, Garlic, Basil, Olive Oil",
      kcal: 110, protein: "3g", fat: "4g", carbs: "15g", sugar: "1g" },
    { n: "French Fries with Cheese Dipping Sauce", c: "Appetizer", h: "Calcium", cost: 12, val: 70, tags: ['carb', 'high_fat', 'fried', 'veg'],
      r_th: "ดิปชีสแคลอรี่สูง", r_en: "High calorie cheese dip.",
      ing_th: "เฟรนช์ฟรายส์, ซอสชีสเชดดาร์, เกลือ", ing_en: "French Fries, Cheddar Cheese Sauce, Salt",
      kcal: 300, protein: "4g", fat: "16g", carbs: "35g", sugar: "1g" },
    { n: "French Fries with Paprika Mayo Dipping Sauce", c: "Appetizer", h: "Spicy", cost: 12, val: 70, tags: ['carb', 'high_fat', 'fried', 'veg'],
      r_th: "มายองเนสรสปาปริก้า", r_en: "Paprika Mayo Dip.",
      ing_th: "เฟรนช์ฟรายส์, ผงปาปริก้า, มายองเนส, มะนาว", ing_en: "French Fries, Paprika Powder, Mayonnaise, Lime Juice",
      kcal: 300, protein: "3g", fat: "18g", carbs: "35g", sugar: "1g" },
    { n: "French Fries with Curry Mayo Dipping Sauce", c: "Appetizer", h: "Aroma", cost: 12, val: 70, tags: ['carb', 'high_fat', 'fried', 'veg'],
      r_th: "มายองเนสรสแกงกะหรี่", r_en: "Curry Mayo Dip.",
      ing_th: "เฟรนช์ฟรายส์, ผงกะหรี่, มายองเนส, ขมิ้น", ing_en: "French Fries, Curry Powder, Mayonnaise, Turmeric",
      kcal: 300, protein: "3g", fat: "18g", carbs: "35g", sugar: "1g" },
    { n: "Steamed Mussels in Tomato Sauce", c: "Appetizer", h: "Zinc, Selenium", cost: 45, val: 220, tags: ['seafood', 'premium'],
      r_th: "แหล่ง Zinc ชั้นยอด บำรุงฮอร์โมน", r_en: "Excellent Zinc source.",
      ing_th: "หอยแมลงภู่ดำ, ซอสมะเขือเทศ, ไวน์ขาว, โหระพา, หอมใหญ่", ing_en: "Black Mussels, Tomato Sauce, White Wine, Basil, Onion",
      kcal: 140, protein: "12g", fat: "4g", carbs: "8g", sugar: "2g" },
    { n: "Baked Spinach with Cheese", c: "Appetizer", h: "Calcium, Iron", cost: 25, val: 120, tags: ['veg', 'high_fat'],
      r_th: "ผักโขมบำรุงเลือด ชีสเสริมแคลเซียม", r_en: "Spinach for iron, Cheese for calcium.",
      ing_th: "ผักโขม, มอสซาเรลล่าชีส, พาเมซานชีส, ครีม, กระเทียม", ing_en: "Spinach, Mozzarella Cheese, Parmesan, Cream, Garlic",
      kcal: 250, protein: "10g", fat: "20g", carbs: "5g", sugar: "1g" },
    { n: "Arancini Parma Ham with Truffle Mayo", c: "Appetizer", h: "Premium Carb", cost: 35, val: 180, tags: ['pork', 'carb', 'fried', 'premium'],
      r_th: "ริซอตโต้ทอดสอดไส้พาร์มาแฮม", r_en: "Fried Risotto Ball with Parma Ham.",
      ing_th: "ข้าวริซอตโต้, พาร์มาแฮม, ทรัฟเฟิลมาโย, ชีส, เกล็ดขนมปัง", ing_en: "Risotto Rice, Parma Ham, Truffle Mayo, Cheese, Breadcrumbs",
      kcal: 280, protein: "8g", fat: "14g", carbs: "30g", sugar: "1g" },
    { n: "Salmon Ball with Spicy Mayo Sauce", c: "Appetizer", h: "Protein (Fish)", cost: 20, val: 90, tags: ['seafood', 'carb', 'fried'],
      r_th: "ลาบแซลมอนทอด", r_en: "Fried Spicy Salmon Balls.",
      ing_th: "เนื้อปลาแซลมอน, เครื่องเทศลาบ, เกล็ดขนมปัง, สไปซี่มาโย, ต้นหอม", ing_en: "Minced Salmon, Spicy Herbs, Breadcrumbs, Spicy Mayo, Spring Onion",
      kcal: 200, protein: "12g", fat: "12g", carbs: "10g", sugar: "1g" },
    { n: "Crispy Fried Shrimp", c: "Appetizer", h: "Calcium", cost: 30, val: 140, tags: ['seafood', 'fried'],
      r_th: "กุ้งทอดทั้งตัว แคลเซียมสูง", r_en: "Whole fried shrimp. High calcium.",
      ing_th: "กุ้งทั้งตัว, แป้งทอดกรอบ, เกลือสมุทร, เลมอน, สไปซี่มาโย", ing_en: "Whole Shrimp, Batter, Sea Salt, Lemon, Spicy Mayo",
      kcal: 250, protein: "18g", fat: "15g", carbs: "12g", sugar: "0g" },
    { n: "Calamari & Chips", c: "Appetizer", h: "Protein (Squid)", cost: 30, val: 150, tags: ['seafood', 'carb', 'fried'],
      r_th: "ปลาหมึกชุบแป้งทอด", r_en: "Fried Squid Rings.",
      ing_th: "ปลาหมึกวง, แป้งทอดกรอบ, เฟรนช์ฟรายส์, ทาร์ทาร์ซอส, เลมอน", ing_en: "Squid Rings, Batter, French Fries, Tartar Sauce, Lemon",
      kcal: 380, protein: "15g", fat: "20g", carbs: "35g", sugar: "1g" },
    { n: "Fish Fingers & Chips", c: "Appetizer", h: "Fish Protein", cost: 25, val: 130, tags: ['seafood', 'carb', 'fried'],
      r_th: "ปลาชุบแป้งทอดทานง่าย", r_en: "Easy to eat fried fish.",
      ing_th: "เนื้อปลาดอลลี่, เกล็ดขนมปัง, เฟรนช์ฟรายส์, เลมอน, ทาร์ทาร์ซอส", ing_en: "Dory Fish Fillet, Breadcrumbs, Fries, Lemon, Tartar Sauce",
      kcal: 350, protein: "14g", fat: "18g", carbs: "32g", sugar: "1g" },
    { n: "Chicken BBQ", c: "Appetizer", h: "Protein", cost: 25, val: 120, tags: ['poultry', 'sugar'],
      r_th: "ไก่บาร์บีคิวรสเข้มข้น", r_en: "Rich BBQ flavored chicken.",
      ing_th: "ปีกไก่บน, ซอสบาร์บีคิวสูตรพิเศษ, งาขาว, น้ำผึ้ง", ing_en: "Chicken Drumettes, Special BBQ Sauce, Sesame Seeds, Honey",
      kcal: 220, protein: "18g", fat: "12g", carbs: "8g", sugar: "6g" },
    { n: "Garlic Bread", c: "Appetizer", h: "Energy", cost: 10, val: 60, tags: ['veg', 'carb'],
      r_th: "หอมกระเทียมแต่เนยเยอะ", r_en: "Aromatic garlic but buttery.",
      ing_th: "ขนมปังบาแก็ตสไลซ์, เนยสด, กระเทียมสับ, พาสลีย์, เกลือ", ing_en: "Sliced Baguette, Butter, Minced Garlic, Parsley, Salt",
      kcal: 150, protein: "3g", fat: "8g", carbs: "18g", sugar: "0g" },

    // --- SOUP ---
    { n: "Lobster Bisque", c: "Soup", h: "Astaxanthin", cost: 50, val: 250, tags: ['seafood', 'premium', 'high_fat'],
      r_th: "ซุปพรีเมียม สารต้านอนุมูลอิสระสูง", r_en: "Premium soup. High antioxidants.",
      ing_th: "สต็อกกุ้งล็อบสเตอร์, ครีมสด, บรั่นดี, เนย, มะเขือเทศเข้มข้น", ing_en: "Lobster Stock, Fresh Cream, Brandy, Butter, Tomato Paste",
      kcal: 180, protein: "6g", fat: "14g", carbs: "8g", sugar: "1g" },
    { n: "Truffle Soup", c: "Soup", h: "Aroma", cost: 40, val: 190, tags: ['veg', 'premium', 'high_fat'],
      r_th: "หอมผ่อนคลาย คุ้มค่า", r_en: "Relaxing aroma. Good value.",
      ing_th: "เห็ดแชมปิญอง, ครีมทรัฟเฟิล, น้ำมันทรัฟเฟิล, ครีม, หัวหอม", ing_en: "Champignon Mushrooms, Truffle Paste, Truffle Oil, Cream, Onion",
      kcal: 160, protein: "3g", fat: "12g", carbs: "10g", sugar: "1g" },
    { n: "Pumpkin & Carrot Soup", c: "Soup", h: "Beta-Carotene", cost: 15, val: 90, tags: ['veg'],
      r_th: "ดีต่อสายตา (วิตามินเอสูง)", r_en: "Great for eyes (High Vit A).",
      ing_th: "ฟักทองญี่ปุ่น, แครอท, หอมใหญ่, น้ำสต็อกผัก, ครีม", ing_en: "Japanese Pumpkin, Carrot, Onion, Vegetable Stock, Cream",
      kcal: 90, protein: "2g", fat: "3g", carbs: "15g", sugar: "3g" },
    { n: "Tomato Soup", c: "Soup", h: "Lycopene", cost: 15, val: 90, tags: ['veg'],
      r_th: "รสเปรี้ยวสดชื่น", r_en: "Tangy and refreshing.",
      ing_th: "มะเขือเทศสด, หอมใหญ่, กระเทียม, ใบโหระพา, น้ำมันมะกอก", ing_en: "Fresh Tomato, Onion, Garlic, Basil, Olive Oil",
      kcal: 70, protein: "2g", fat: "2g", carbs: "12g", sugar: "4g" },
    { n: "Potato Cream Soup", c: "Soup", h: "Energy", cost: 10, val: 80, tags: ['pork', 'carb', 'high_fat'],
      r_th: "แป้งและครีม ตัดกำลัง", r_en: "Starch and cream. Filler.",
      ing_th: "มันฝรั่ง, ครีม, เบคอนกรอบโรยหน้า, ต้นหอม, เนย", ing_en: "Potato, Cream, Crispy Bacon Bits, Spring Onion, Butter",
      kcal: 200, protein: "4g", fat: "12g", carbs: "20g", sugar: "0g" },

    // --- MAIN DISH ---
    { n: "Australian Grain-Fed 120-Day Striploin Steak", c: "Main Dish", h: "Protein, Iron", cost: 130, val: 550, tags: ['beef', 'premium', 'high_fat'],
      r_th: "เนื้อนุ่ม รสเข้มข้น โปรตีนสูง", r_en: "Tender, rich flavor. High Protein.",
      ing_th: "เนื้อสันนอกออสเตรเลีย (Grain-Fed 120 วัน), มันบด, ซอสพริกไทยดำ, ผักย่าง", ing_en: "Australian Grain-Fed Striploin (120 Days), Mashed Potato, Black Pepper Sauce, Roasted Veg",
      kcal: 350, protein: "35g", fat: "22g", carbs: "0g", sugar: "0g" },
    { n: "Pan-Seared Sea Bass with Pumpkin Sauce", c: "Main Dish", h: "Lean Protein", cost: 60, val: 280, tags: ['seafood', 'premium'],
      r_th: "ปลาเนื้อขาว ย่อยง่าย ไขมันต่ำ", r_en: "White fish, easy to digest.",
      ing_th: "ปลากะพงขาว, ซอสฟักทอง, ผักย่าง, ถั่วแระญี่ปุ่น, เลมอน", ing_en: "Sea Bass Fillet, Pumpkin Puree Sauce, Roasted Vegetables, Edamame, Lemon",
      kcal: 240, protein: "28g", fat: "10g", carbs: "8g", sugar: "1g" },
    { n: "Smoked Pork Belly with Red Wine Sauce", c: "Main Dish", h: "Protein, Fat", cost: 70, val: 260, tags: ['pork', 'high_fat'],
      r_th: "อร่อยแต่มันเยอะ", r_en: "Delicious but fatty.",
      ing_th: "หมูสามชั้นรมควัน, ซอสไวน์แดง, มันบด, หน่อไม้ฝรั่ง", ing_en: "Smoked Pork Belly, Red Wine Reduction, Mashed Potato, Asparagus",
      kcal: 450, protein: "20g", fat: "35g", carbs: "10g", sugar: "2g" },
    { n: "Steak with Cafe de Paris Sauce", c: "Main Dish", h: "Protein", cost: 100, val: 450, tags: ['beef', 'premium', 'high_fat'],
      r_th: "สเต็กเนื้อกับซอสเนยสูตรพิเศษ", r_en: "Beef steak with butter sauce.",
      ing_th: "สเต็กเนื้อสันนอก, ซอสเนยสมุนไพร Cafe de Paris, เฟรนช์ฟรายส์", ing_en: "Striploin Steak, Cafe de Paris Herb Butter, French Fries",
      kcal: 400, protein: "30g", fat: "30g", carbs: "2g", sugar: "0g" },
    { n: "Chicken Roll with Parmigiano Sauce", c: "Main Dish", h: "Calcium", cost: 40, val: 190, tags: ['poultry', 'pork', 'carb', 'high_fat'],
      r_th: "ไก่ม้วนแฮมชีส", r_en: "Chicken stuffed with ham & cheese.",
      ing_th: "อกไก่ม้วน, แฮม, ชีสมอสซาเรลล่า, ซอสครีมพาร์มิซาน, มันบด", ing_en: "Rolled Chicken Breast, Ham, Mozzarella, Parmesan Cream Sauce, Mashed Potato",
      kcal: 280, protein: "25g", fat: "14g", carbs: "12g", sugar: "1g" },
    { n: "Salmon Steak", c: "Main Dish", h: "Omega-3", cost: 80, val: 320, tags: ['seafood', 'premium'],
      r_th: "แซลมอนย่าง โอเมก้า 3 สูง", r_en: "Grilled Salmon. High Omega-3.",
      ing_th: "สเต็กปลาแซลมอน, ซอสครีมมะนาว, ถั่วแระญี่ปุ่น, มันบด", ing_en: "Salmon Steak, Lemon Cream Sauce, Edamame, Mashed Potato",
      kcal: 320, protein: "30g", fat: "20g", carbs: "5g", sugar: "0g" },
    { n: "Smoked Duck", c: "Main Dish", h: "Iron, Mono-Fat", cost: 50, val: 240, tags: ['poultry', 'premium'],
      r_th: "อกเป็ดนุ่ม หอมควัน", r_en: "Soft smoked duck breast.",
      ing_th: "อกเป็ดรมควัน, ซอสส้ม, สลัดส้ม, มันบด", ing_en: "Smoked Duck Breast, Orange Glaze, Orange Salad, Mashed Potato",
      kcal: 220, protein: "18g", fat: "14g", carbs: "6g", sugar: "4g" },
    { n: "BBQ Pork Ribs", c: "Main Dish", h: "Collagen", cost: 55, val: 280, tags: ['pork', 'sugar'],
      r_th: "ซี่โครงหมูเปื่อยซอสฉ่ำ", r_en: "Tender ribs in BBQ sauce.",
      ing_th: "ซี่โครงหมูตุ๋น, ซอสบาร์บีคิวเข้มข้น, สลัดโคลสลอว์, งาขาว", ing_en: "Slow-cooked Pork Ribs, Rich BBQ Sauce, Coleslaw, Sesame Seeds",
      kcal: 350, protein: "22g", fat: "20g", carbs: "15g", sugar: "10g" },
    { n: "Chicken Milanese", c: "Main Dish", h: "Protein, Carb", cost: 40, val: 200, tags: ['poultry', 'carb', 'fried'],
      r_th: "ไก่ชุบเกล็ดขนมปังทอดกรอบ", r_en: "Breaded and fried chicken cutlet.",
      ing_th: "อกไก่ทุบแบน, เกล็ดขนมปัง, เลมอน, สลัด, ซอสทาร์ทาร์", ing_en: "Pounded Chicken Breast, Breadcrumbs, Lemon Wedge, Side Salad, Tartar Sauce",
      kcal: 320, protein: "20g", fat: "16g", carbs: "25g", sugar: "0g" },
    { n: "Mixed Grilled Sausage", c: "Main Dish", h: "Protein, Sodium", cost: 35, val: 180, tags: ['pork', 'poultry', 'high_fat'],
      r_th: "ไส้กรอกรวม", r_en: "Mixed sausages.",
      ing_th: "ไส้กรอกหมูรมควัน, ไส้กรอกไก่เครื่องเทศ, มันบด, ซอสเกรวี่, กะหล่ำดอง", ing_en: "Smoked Pork Sausage, Spiced Chicken Sausage, Mashed Potato, Gravy, Sauerkraut",
      kcal: 320, protein: "14g", fat: "28g", carbs: "5g", sugar: "1g" },

    // --- SEAFOOD ---
    { n: "Oysters on Ice", c: "Seafood", h: "Zinc High", cost: 60, val: 300, tags: ['seafood', 'raw', 'premium'],
      r_th: "หอยนางรมสด Zinc สูง", r_en: "Fresh Oysters. High Zinc.",
      ing_th: "หอยนางรมสดนำเข้า, เลมอน, น้ำจิ้มซีฟู้ด, หอมเจียว, น้ำพริกเผา", ing_en: "Imported Fresh Oysters, Lemon, Seafood Sauce, Fried Shallots, Chili Paste",
      kcal: 60, protein: "8g", fat: "2g", carbs: "3g", sugar: "0g" },
    { n: "Mussels on Ice", c: "Seafood", h: "Zinc", cost: 40, val: 220, tags: ['seafood', 'premium'],
      r_th: "หอยแมลงภู่เย็น", r_en: "Chilled Mussels.",
      ing_th: "หอยแมลงภู่ชิลี, น้ำจิ้มซีฟู้ดมะนาวสด", ing_en: "Chilean Mussels, Lime Seafood Sauce",
      kcal: 90, protein: "12g", fat: "2g", carbs: "4g", sugar: "0g" },
    { n: "Shrimp on Ice", c: "Seafood", h: "Astaxanthin", cost: 40, val: 280, tags: ['seafood', 'premium'],
      r_th: "กุ้งเย็น เนื้อเด้ง", r_en: "Chilled Shrimp.",
      ing_th: "กุ้งขาวลวกเย็น, น้ำจิ้มซีฟู้ดรสจัด", ing_en: "Chilled Boiled White Shrimp, Spicy Seafood Sauce",
      kcal: 120, protein: "22g", fat: "1g", carbs: "0g", sugar: "0g" },

    // --- PIZZA ---
    { n: "Margherita Pizza", c: "Pizza", h: "Lycopene", cost: 15, val: 120, tags: ['veg', 'carb'],
      r_th: "พิซซ่าหน้าชีสและมะเขือเทศ", r_en: "Cheese & Tomato Pizza.",
      ing_th: "แป้งพิซซ่าโฮมเมด, ซอสมะเขือเทศ, ชีสมอสซาเรลล่าสด, ใบโหระพา, น้ำมันมะกอก", ing_en: "Homemade Dough, Tomato Sauce, Fresh Mozzarella, Basil Leaves, Olive Oil",
      kcal: 250, protein: "10g", fat: "8g", carbs: "35g", sugar: "2g" },
    { n: "Diavola Pizza", c: "Pizza", h: "Capsaicin", cost: 20, val: 150, tags: ['pork', 'carb'],
      r_th: "พิซซ่าหน้าซาลามี่เผ็ด", r_en: "Spicy Salami Pizza.",
      ing_th: "แป้งพิซซ่า, ซาลามี่รสเผ็ด, พริกแห้ง, ชีสมอสซาเรลล่า, ซอสมะเขือเทศ", ing_en: "Dough, Spicy Salami, Dried Chili, Mozzarella Cheese, Tomato Sauce",
      kcal: 280, protein: "12g", fat: "14g", carbs: "32g", sugar: "2g" },
    { n: "Formaggi Pizza", c: "Pizza", h: "Calcium", cost: 25, val: 180, tags: ['veg', 'carb', 'high_fat'],
      r_th: "พิซซ่ารวมชีส", r_en: "Four Cheese Pizza.",
      ing_th: "แป้งพิซซ่า, มอสซาเรลล่า, กอร์กอนโซล่า, พาเมซาน, บรี, น้ำผึ้ง", ing_en: "Dough, Mozzarella, Gorgonzola, Parmesan, Brie, Honey",
      kcal: 320, protein: "14g", fat: "18g", carbs: "30g", sugar: "3g" },
    { n: "Salmon & Spinach Calzone", c: "Pizza", h: "Omega-3", cost: 30, val: 200, tags: ['seafood', 'carb', 'high_fat'],
      r_th: "พัฟพิซซ่าไส้แซลมอนผักโขม", r_en: "Folded pizza with salmon & spinach.",
      ing_th: "แป้งพิซซ่าพับ, เนื้อปลาแซลมอน, ผักโขมผัดเนย, ชีสมอสซาเรลล่า, ครีม", ing_en: "Folded Dough, Salmon Chunks, Sautéed Spinach, Mozzarella Cheese, Cream",
      kcal: 350, protein: "18g", fat: "16g", carbs: "38g", sugar: "1g" },
    { n: "Mixed Mushroom Pizza", c: "Pizza", h: "Fiber", cost: 20, val: 160, tags: ['veg', 'carb'],
      r_th: "พิซซ่าหน้าเห็ดรวม", r_en: "Mixed Mushroom Pizza.",
      ing_th: "แป้งพิซซ่า, เห็ดแชมปิญอง, เห็ดออรินจิ, เห็ดชิเมจิ, น้ำมันทรัฟเฟิล, ชีส", ing_en: "Dough, Champignon, Eringi, Shimeji Mushrooms, Truffle Oil, Cheese",
      kcal: 240, protein: "8g", fat: "8g", carbs: "35g", sugar: "1g" },
    { n: "Truffle Cream Pizza", c: "Pizza", h: "Aroma", cost: 35, val: 220, tags: ['veg', 'carb', 'premium'],
      r_th: "พิซซ่าครีมทรัฟเฟิล", r_en: "Truffle Cream Pizza.",
      ing_th: "แป้งพิซซ่า, ซอสครีมทรัฟเฟิลดำ, ชีสมอสซาเรลล่า, เห็ดสไลซ์, น้ำมันทรัฟเฟิล", ing_en: "Dough, Black Truffle Cream Sauce, Mozzarella, Sliced Mushrooms, Truffle Oil",
      kcal: 290, protein: "10g", fat: "15g", carbs: "30g", sugar: "1g" },

    // --- PASTA ---
    { n: "Ham & Mushroom Penne Alfredo", c: "Pasta", h: "Energy", cost: 20, val: 160, tags: ['pork', 'carb', 'high_fat'],
      r_th: "พาสต้าครีมซอสแฮมเห็ด", r_en: "Creamy Ham & Mushroom Pasta.",
      ing_th: "เส้นเพนเน่, แฮมหมู, เห็ดแชมปิญอง, ครีมซอส, พาเมซานชีส, พาสลีย์", ing_en: "Penne Pasta, Pork Ham, Champignon Mushroom, Cream Sauce, Parmesan, Parsley",
      kcal: 350, protein: "12g", fat: "18g", carbs: "40g", sugar: "1g" },
    { n: "Capellini AOP Bacon", c: "Pasta", h: "Energy", cost: 20, val: 150, tags: ['pork', 'carb', 'high_fat'],
      r_th: "ผัดพริกแห้งเบคอน", r_en: "Spicy Aglio Olio with Bacon.",
      ing_th: "เส้นแองเจิลแฮร์, เบคอนกรอบ, พริกแห้ง, กระเทียม, น้ำมันมะกอก, ใบโหระพา", ing_en: "Angel Hair Pasta, Crispy Bacon, Dried Chili, Garlic, Olive Oil, Basil",
      kcal: 380, protein: "10g", fat: "20g", carbs: "42g", sugar: "0g" },
    { n: "Capellini AOP Shrimp", c: "Pasta", h: "Protein", cost: 25, val: 180, tags: ['seafood', 'carb'],
      r_th: "ผัดพริกแห้งกุ้ง", r_en: "Spicy Aglio Olio with Shrimp.",
      ing_th: "เส้นแองเจิลแฮร์, กุ้งขาว, พริกแห้ง, กระเทียม, โหระพา, น้ำมันมะกอก", ing_en: "Angel Hair Pasta, White Shrimp, Dried Chili, Garlic, Basil, Olive Oil",
      kcal: 320, protein: "15g", fat: "10g", carbs: "42g", sugar: "0g" },
    { n: "Linguine alle Vongole", c: "Pasta", h: "Iron", cost: 35, val: 220, tags: ['seafood', 'carb', 'premium'],
      r_th: "หอยลายผัดไวน์ขาว", r_en: "Clams in White Wine Sauce.",
      ing_th: "เส้นลิงกวินี่, หอยลายทั้งเปลือก, ไวน์ขาว, กระเทียม, พาสลีย์, พริกแห้ง", ing_en: "Linguine Pasta, Whole Clams, White Wine, Garlic, Parsley, Dried Chili",
      kcal: 300, protein: "15g", fat: "8g", carbs: "42g", sugar: "0g" },
    { n: "Rigatoni Puttanesca", c: "Pasta", h: "Lycopene", cost: 25, val: 180, tags: ['seafood', 'carb'],
      r_th: "ซอสมะเขือเทศรสจัด (มีแอนโชวี่)", r_en: "Spicy Tomato Sauce (Anchovy).",
      ing_th: "เส้นริกาโตนี, มะกอกดำ, เคเปอร์, ปลาแอนโชวี่, ซอสมะเขือเทศ, กระเทียม", ing_en: "Rigatoni, Black Olives, Capers, Anchovy Fillets, Tomato Sauce, Garlic",
      kcal: 280, protein: "8g", fat: "8g", carbs: "45g", sugar: "2g" },
    { n: "Rigatoni Seafood", c: "Pasta", h: "Protein Mix", cost: 40, val: 240, tags: ['seafood', 'carb', 'premium'],
      r_th: "พาสต้ารวมมิตรทะเล", r_en: "Mixed Seafood Pasta.",
      ing_th: "เส้นริกาโตนี, กุ้ง, ปลาหมึกวง, หอยแมลงภู่, ซอสมะเขือเทศ, ไวน์ขาว", ing_en: "Rigatoni, Shrimp, Squid Rings, Mussels, Tomato Sauce, White Wine",
      kcal: 320, protein: "20g", fat: "8g", carbs: "42g", sugar: "2g" },
    { n: "Capellini AOP Australian Beef", c: "Pasta", h: "Protein", cost: 40, val: 200, tags: ['beef', 'carb'],
      r_th: "ผัดพริกแห้งเนื้อวัว", r_en: "Spicy Aglio Olio with Beef.",
      ing_th: "เส้นแองเจิลแฮร์, เนื้อวัวออสเตรเลียสไลซ์, พริกแห้ง, กระเทียม, น้ำมันมะกอก", ing_en: "Angel Hair Pasta, Sliced Australian Beef, Dried Chili, Garlic, Olive Oil",
      kcal: 350, protein: "20g", fat: "15g", carbs: "40g", sugar: "0g" },
    { n: "Spaghetti Carbonara", c: "Pasta", h: "Energy", cost: 30, val: 180, tags: ['pork', 'carb', 'high_fat'],
      r_th: "คาโบนาร่าครีมข้น", r_en: "Creamy Carbonara.",
      ing_th: "เส้นสปาเก็ตตี้, เบคอน, ครีมสด, ไข่แดง, พาเมซานชีส, พริกไทยดำ", ing_en: "Spaghetti, Bacon, Fresh Cream, Egg Yolk, Parmesan Cheese, Black Pepper",
      kcal: 450, protein: "15g", fat: "25g", carbs: "45g", sugar: "0g" },
    { n: "Fettuccine with Truffle Cream Sauce", c: "Pasta", h: "Aroma", cost: 40, val: 240, tags: ['veg', 'carb', 'premium', 'high_fat'],
      r_th: "พาสต้าครีมทรัฟเฟิล", r_en: "Truffle Cream Pasta.",
      ing_th: "เส้นเฟตตูชินี่, ครีมทรัฟเฟิล, น้ำมันทรัฟเฟิล, เห็ดแชมปิญอง, พาเมซานชีส", ing_en: "Fettuccine, Truffle Cream, Truffle Oil, Champignon, Parmesan",
      kcal: 400, protein: "10g", fat: "22g", carbs: "42g", sugar: "1g" },
    { n: "Seafood Pesto Spaghetti", c: "Pasta", h: "Herbs", cost: 35, val: 220, tags: ['seafood', 'carb', 'premium'],
      r_th: "พาสต้าซอสโหระพาซีฟู้ด", r_en: "Seafood Pesto Pasta.",
      ing_th: "เส้นสปาเก็ตตี้, กุ้ง, ปลาหมึก, ซอสเพสโต้ (โหระพา/ถั่วสน/ชีส/น้ำมันมะกอก)", ing_en: "Spaghetti, Shrimp, Squid, Pesto Sauce (Basil/Pine Nuts/Cheese/Olive Oil)",
      kcal: 380, protein: "18g", fat: "18g", carbs: "40g", sugar: "0g" },

    // --- DESSERT ---
    { n: "Cheesecake", c: "Dessert", h: "Calcium", cost: 25, val: 120, tags: ['sugar', 'high_fat', 'veg'],
      r_th: "ชีสเค้กเนื้อเนียน", r_en: "Smooth Cheesecake.",
      ing_th: "ครีมชีส, แครกเกอร์บด, เนย, น้ำตาล, ผลไม้สด", ing_en: "Cream Cheese, Crushed Crackers, Butter, Sugar, Fresh Fruit",
      kcal: 320, protein: "6g", fat: "22g", carbs: "25g", sugar: "18g" },
    { n: "Avocado Panna Cotta", c: "Dessert", h: "Healthy Fats", cost: 30, val: 140, tags: ['sugar', 'premium'],
      r_th: "พานาคอตต้าอะโวคาโด", r_en: "Avocado Panna Cotta.",
      ing_th: "เนื้ออะโวคาโดปั่น, วิปปิ้งครีม, นมสด, เจลาติน, น้ำผึ้ง", ing_en: "Pureed Avocado, Whipping Cream, Fresh Milk, Gelatin, Honey",
      kcal: 220, protein: "4g", fat: "18g", carbs: "12g", sugar: "8g" },
    { n: "Chocolate Mousse", c: "Dessert", h: "Antioxidant", cost: 25, val: 120, tags: ['sugar', 'high_fat', 'veg'],
      r_th: "มูสช็อกโกแลตเข้มข้น", r_en: "Rich Chocolate Mousse.",
      ing_th: "ดาร์กช็อกโกแลต 70%, ไข่ไก่, วิปปิ้งครีม, เนย", ing_en: "70% Dark Chocolate, Eggs, Whipping Cream, Butter",
      kcal: 280, protein: "4g", fat: "20g", carbs: "22g", sugar: "18g" },
    { n: "Apple Mousse Crumble", c: "Dessert", h: "Fruit Fiber", cost: 25, val: 130, tags: ['sugar', 'carb', 'veg'],
      r_th: "มูสแอปเปิ้ลและครัมเบิ้ลกรอบ", r_en: "Apple Mousse with Crumble.",
      ing_th: "เนื้อแอปเปิ้ลเขียว, ครีม, แป้งครัมเบิ้ล, อบเชย, น้ำตาล", ing_en: "Green Apple Pulp, Cream, Crumble Dough, Cinnamon, Sugar",
      kcal: 260, protein: "2g", fat: "12g", carbs: "30g", sugar: "22g" },
    { n: "Strawberry Cheesecake Ice Cream", c: "Dessert", h: "Sweet", cost: 20, val: 80, tags: ['sugar', 'high_fat', 'veg'],
      r_th: "ไอศกรีมรสสตอเบอรี่ชีสเค้ก", r_en: "Strawberry Cheesecake Ice Cream.",
      ing_th: "นมสด, เนื้อสตรอเบอรี่, ครีมชีส, ชิ้นบิสกิต, น้ำตาล", ing_en: "Fresh Milk, Strawberry Chunks, Cream Cheese, Biscuit Pieces, Sugar",
      kcal: 200, protein: "3g", fat: "10g", carbs: "25g", sugar: "22g" },
    { n: "Cookie & Cream Ice Cream", c: "Dessert", h: "Sweet", cost: 20, val: 80, tags: ['sugar', 'high_fat', 'veg'],
      r_th: "ไอศกรีมคุกกี้แอนด์ครีม", r_en: "Cookie & Cream Ice Cream.",
      ing_th: "นมสด, คุกกี้โอริโอ้บด, ครีม, น้ำตาล", ing_en: "Fresh Milk, Crushed Oreo Cookies, Cream, Sugar",
      kcal: 220, protein: "3g", fat: "12g", carbs: "26g", sugar: "23g" },
    { n: "Vanilla Macadamia Ice Cream", c: "Dessert", h: "Nut Fat", cost: 25, val: 100, tags: ['sugar', 'high_fat', 'premium', 'veg'],
      r_th: "ไอศกรีมวานิลลาแมคคาเดเมีย", r_en: "Vanilla Macadamia Ice Cream.",
      ing_th: "นมสด, ฝักวานิลลาแท้, ถั่วแมคคาเดเมียอบ, น้ำตาล, ครีม", ing_en: "Fresh Milk, Real Vanilla Bean, Roasted Macadamia Nuts, Sugar, Cream",
      kcal: 240, protein: "4g", fat: "16g", carbs: "24g", sugar: "20g" },
    { n: "Red Berry Sorbet", c: "Dessert", h: "Vit C", cost: 25, val: 90, tags: ['sugar', 'veg'],
      r_th: "ซอร์เบท์เบอร์รี่เปรี้ยวหวาน", r_en: "Red Berry Sorbet.",
      ing_th: "ราสเบอร์รี่, สตรอเบอร์รี่, แครนเบอร์รี่, น้ำเชื่อม, น้ำมะนาว", ing_en: "Raspberry, Strawberry, Cranberry, Syrup, Lemon Juice",
      kcal: 100, protein: "0g", fat: "0g", carbs: "25g", sugar: "24g" },
    { n: "Chocolate Lava with Ice Cream", c: "Dessert", h: "Indulgence", cost: 40, val: 160, tags: ['sugar', 'high_fat', 'premium', 'veg'],
      r_th: "เค้กช็อกโกแลตลาวา", r_en: "Chocolate Lava Cake.",
      ing_th: "ดาร์กช็อกโกแลต, เนยสด, ไข่ไก่, แป้งเค้ก, น้ำตาล, ไอศกรีมวานิลลา", ing_en: "Dark Chocolate, Fresh Butter, Eggs, Cake Flour, Sugar, Vanilla Ice Cream",
      kcal: 350, protein: "6g", fat: "22g", carbs: "35g", sugar: "28g" },
    { n: "Crème Brulee", c: "Dessert", h: "Texture", cost: 30, val: 140, tags: ['sugar', 'high_fat', 'veg'],
      r_th: "คัสตาร์ดหน้าไหม้", r_en: "Custard with burnt sugar top.",
      ing_th: "ไข่แดง, วิปปิ้งครีม, ฝักวานิลลา, น้ำตาลทรายแดง (เบิร์นไฟ)", ing_en: "Egg Yolk, Whipping Cream, Vanilla Bean, Brown Sugar (Torched)",
      kcal: 300, protein: "4g", fat: "25g", carbs: "15g", sugar: "14g" },
    { n: "Mille-Feuille", c: "Dessert", h: "Skill Value", cost: 35, val: 180, tags: ['sugar', 'carb', 'premium', 'veg'],
      r_th: "แป้งพายชั้นกรอบครีมสด", r_en: "Layered puff pastry with cream.",
      ing_th: "แป้งพายชั้น (Puff Pastry), ครีมคัสตาร์ดวานิลลา, ผลไม้สด, น้ำตาลไอซิ่ง", ing_en: "Puff Pastry, Vanilla Custard Cream, Fresh Fruit, Icing Sugar",
      kcal: 280, protein: "4g", fat: "18g", carbs: "26g", sugar: "15g" },
    { n: "Tiramisu", c: "Dessert", h: "Caffeine", cost: 35, val: 160, tags: ['sugar', 'high_fat', 'premium', 'veg'],
      r_th: "เค้กทีรามิสุหอมกาแฟ", r_en: "Coffee flavored Italian dessert.",
      ing_th: "มาสคาร์โปเนชีส, กาแฟเอสเพรสโซ่, ขนมปังเลดี้ฟิงเกอร์, ผงโกโก้, ไข่ไก่", ing_en: "Mascarpone Cheese, Espresso Coffee, Ladyfingers, Cocoa Powder, Eggs",
      kcal: 320, protein: "6g", fat: "24g", carbs: "20g", sugar: "16g" }
];

export const beverageDB: MenuItem[] = [
    // Soft Drinks
    { n: "Chang Drinking Water", c: "Soft Drinks", h: "Hydration", cost: 5, val: 20, tags: [],
      r_th: "ดีที่สุดสำหรับการเติมน้ำให้ร่างกาย ช่วยล้างลิ้นระหว่างมื้ออาหาร", r_en: "Essential for hydration and palate cleansing between courses.",
      ing_th: "น้ำแร่ธรรมชาติ 100%", ing_en: "100% Natural Mineral Water",
      kcal: 0, protein: "0g", fat: "0g", carbs: "0g", sugar: "0g" },
    { n: "Est-Cola", c: "Soft Drinks", h: "Sugar Rush", cost: 10, val: 40, tags: ['sugar'],
      r_th: "น้ำตาลสูง (36g) กระตุ้นอินซูลิน ควรดื่มแต่น้อยเพื่อความสดชื่น", r_en: "High sugar (36g). Spikes insulin. Drink sparingly for energy boost.",
      ing_th: "น้ำตาล 11%, คาเฟอีน, ก๊าซคาร์บอนไดออกไซด์, สีคาราเมล", ing_en: "Sugar 11%, Caffeine, Carbonated Water, Caramel Color",
      kcal: 140, protein: "0g", fat: "0g", carbs: "36g", sugar: "36g" },
    { n: "Est-Cola Sugar Free", c: "Soft Drinks", h: "Zero Cal", cost: 10, val: 40, tags: [],
      r_th: "ทางเลือกดีสำหรับคนอยากหวานแต่กลัวอ้วน ไม่มีแคลอรี่", r_en: "Good option for sweet cravings without calories or insulin spikes.",
      ing_th: "สารให้ความหวาน (แอสปาร์แตม), ก๊าซคาร์บอนไดออกไซด์", ing_en: "Artificial Sweetener (Aspartame), Carbonated Water",
      kcal: 0, protein: "0g", fat: "0g", carbs: "0g", sugar: "0g" },
    { n: "Schweppes Ginger Ale", c: "Soft Drinks", h: "Digestion", cost: 15, val: 50, tags: ['sugar'],
      r_th: "กลิ่นขิงช่วยขับลมแก้ท้องอืด แต่น้ำตาลยังสูง", r_en: "Ginger aroma aids digestion, but sugar content is significant.",
      ing_th: "น้ำตาล 10%, กลิ่นขิงธรรมชาติ, กรดซิตริก, โซดา", ing_en: "Sugar 10%, Natural Ginger Flavor, Citric Acid, Soda Water",
      kcal: 120, protein: "0g", fat: "0g", carbs: "30g", sugar: "30g" },
    { n: "Schweppes Tonic Water", c: "Soft Drinks", h: "Bitter", cost: 15, val: 50, tags: ['sugar'],
      r_th: "รสขมจากควินิน ตัดเลี่ยนอาหารมันได้ดี", r_en: "Bitter Quinine cuts through fatty foods well.",
      ing_th: "น้ำตาล 9%, ควินิน, กลิ่นผลไม้รสเปรี้ยว, โซดา", ing_en: "Sugar 9%, Quinine, Citrus Flavor, Soda Water",
      kcal: 120, protein: "0g", fat: "0g", carbs: "30g", sugar: "30g" },

    // Mocktails
    { n: "VP Sling", c: "Mocktails", h: "Refresh", cost: 20, val: 120, tags: ['sugar'],
      r_th: "สดชื่นด้วยผลไม้รสเปรี้ยวหวาน วิตามินซีสูง", r_en: "Refreshing sweet & sour blend. High Vitamin C.",
      ing_th: "น้ำสับปะรด, น้ำส้ม, น้ำมะนาว, น้ำเชื่อมทับทิม, โซดา", ing_en: "Pineapple Juice, Orange Juice, Lime Juice, Grenadine Syrup, Soda",
      kcal: 110, protein: "0g", fat: "0g", carbs: "28g", sugar: "26g" },
    { n: "Green Floral", c: "Mocktails", h: "Aroma", cost: 20, val: 120, tags: ['sugar'],
      r_th: "กลิ่นหอมดอกไม้ช่วยผ่อนคลาย ดื่มง่าย", r_en: "Relaxing floral aroma. Easy to drink.",
      ing_th: "ไซรัปกลิ่นเอลเดอร์ฟลาวเวอร์, น้ำแอปเปิ้ลเขียว, โซดา, มะนาว", ing_en: "Elderflower Syrup, Green Apple Juice, Soda, Lime Slice",
      kcal: 95, protein: "0g", fat: "0g", carbs: "24g", sugar: "22g" },
    { n: "Lychee Blossom", c: "Mocktails", h: "Sweet Floral", cost: 20, val: 120, tags: ['sugar'],
      r_th: "หอมหวานลิ้นจี่ผสานกลิ่นดอกไม้", r_en: "Sweet Lychee with floral notes.",
      ing_th: "น้ำลิ้นจี่, ไซรัปกุหลาบ, น้ำมะนาว, โซดา", ing_en: "Lychee Juice, Rose Syrup, Lime Juice, Soda",
      kcal: 105, protein: "0g", fat: "0g", carbs: "26g", sugar: "25g" },
    { n: "Yuzu Honey Sparkling", c: "Mocktails", h: "Citrus Zest", cost: 20, val: 120, tags: ['sugar'],
      r_th: "ส้มยูซุและน้ำผึ้ง สดชื่นแก้เลี่ยน", r_en: "Yuzu & Honey. Zesty palate cleanser.",
      ing_th: "น้ำส้มยูซุ, น้ำผึ้งป่า, โซดา, ใบสะระแหน่", ing_en: "Yuzu Puree, Wild Honey, Soda, Mint Leaves",
      kcal: 100, protein: "0g", fat: "0g", carbs: "25g", sugar: "24g" },

    // Coffee
    { n: "Espresso", c: "Coffee (Hot Only)", h: "Caffeine", cost: 15, val: 60, tags: [],
      r_th: "เข้มข้น กระตุ้นการเผาผลาญหลังมื้ออาหาร", r_en: "Intense. Boosts metabolism after a meal.",
      ing_th: "เมล็ดกาแฟอาราบิก้าคั่วกลาง-เข้ม 100%", ing_en: "100% Medium-Dark Roast Arabica Beans",
      kcal: 5, protein: "0g", fat: "0g", carbs: "1g", sugar: "0g" },
    { n: "Americano", c: "Coffee (Hot Only)", h: "Low Cal", cost: 15, val: 70, tags: [],
      r_th: "ช่วยย่อยอาหาร ดีต่อสุขภาพ ไม่มีแคลอรี่", r_en: "Aids digestion. Healthy choice with zero calories.",
      ing_th: "ช็อตเอสเพรสโซ่เข้มข้น, น้ำร้อน", ing_en: "Double Espresso Shot, Hot Water",
      kcal: 5, protein: "0g", fat: "0g", carbs: "1g", sugar: "0g" },
    { n: "Cappuccino", c: "Coffee (Hot Only)", h: "Milk Foam", cost: 15, val: 80, tags: ['high_fat'],
      r_th: "ฟองนมนุ่มละมุน แต่อาจแน่นท้องหากทานอิ่มจัด", r_en: "Smooth milk foam. Might be heavy after a full meal.",
      ing_th: "เอสเพรสโซ่, นมสดร้อน, ฟองนมหนานุ่ม", ing_en: "Espresso, Steamed Fresh Milk, Thick Milk Foam",
      kcal: 80, protein: "4g", fat: "4g", carbs: "6g", sugar: "6g" },
    { n: "Caffe Latte", c: "Coffee (Hot Only)", h: "Milky", cost: 15, val: 80, tags: ['high_fat'],
      r_th: "รสนมนำ ดื่มง่าย เหมาะสำหรับปิดท้ายมื้อเบาๆ", r_en: "Milky and mild. Good finish for a lighter meal.",
      ing_th: "เอสเพรสโซ่, นมสดร้อนปริมาณมาก, ฟองนมบาง", ing_en: "Espresso, Generous Steamed Milk, Microfoam",
      kcal: 100, protein: "5g", fat: "5g", carbs: "8g", sugar: "8g" },

    // Special
    { n: "Chang Cold Brew", c: "Special Drink", h: "Malt Aroma", cost: 25, val: 120, tags: ['carb', 'premium'],
      r_th: "นุ่มลื่นจากมอลต์ 100% ล้างไขมันในปากได้ดีเยี่ยม", r_en: "Smooth 100% Malt. Excellent for cleansing palate of fats.",
      ing_th: "ข้าวมอลต์, ฮอปส์, น้ำแร่ธรรมชาติ, ยีสต์หมักเย็น", ing_en: "Barley Malt, Hops, Mineral Water, Cold Fermented Yeast",
      kcal: 130, protein: "1g", fat: "0g", carbs: "12g", sugar: "0g" }
];

export const calculateStatus = (item: MenuItem, diet: DietaryStyle): number => {
  if (!item) return 1;
  const tags = item.tags || [];

  // 1. Check restrictions (Avoids)
  let isAvoid = false;
  switch (diet) {
    case 'vegetarian':
      if (tags.includes('beef') || tags.includes('pork') || tags.includes('poultry') || tags.includes('seafood')) isAvoid = true;
      break;
    case 'pescatarian':
       if (tags.includes('beef') || tags.includes('pork') || tags.includes('poultry')) isAvoid = true;
       break;
    case 'keto':
       if (tags.includes('carb') || tags.includes('sugar') || tags.includes('fried')) isAvoid = true;
       break;
    case 'omnivore':
    default:
       // Omnivores might want to avoid low-value carbs unless premium or has some other benefit
       if (tags.includes('carb') && !tags.includes('premium') && !tags.includes('veg') && !tags.includes('seafood')) {
           // We generally recommend against fillers
       }
       break;
  }

  if (isAvoid) return 0;

  // 2. Check Premium (Must Try) - If it passed the avoid check, and is premium, it's a Must Try.
  if (tags.includes('premium')) return 3;

  // 3. Check Recommended vs Neutral
  switch (diet) {
    case 'vegetarian':
      if (tags.includes('veg')) return 2;
      break;
    case 'pescatarian':
      if (tags.includes('seafood') || tags.includes('veg')) return 2;
      break;
    case 'keto':
      if (tags.includes('high_fat') || tags.includes('protein')) return 2;
      break;
    case 'omnivore':
    default:
      // Recommend main proteins and veg
      if (tags.includes('veg') || tags.includes('seafood') || tags.includes('beef') || tags.includes('poultry') || tags.includes('pork')) return 2;
      // Downgrade basic carbs to 1 if they weren't caught above, though non-premium carbs likely return 1 anyway
      if (tags.includes('carb')) return 1;
      break;
  }

  return 1;
};
